/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 创建项目 */
        post: operations["createProject"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{projectId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 查询项目 */
        get: operations["getProject"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{projectId}/applications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 创建应用 */
        post: operations["createApplication"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/applications/{applicationId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 查询应用 */
        get: operations["getApplication"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/applications/{applicationId}/deployment-targets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 创建部署目标 */
        post: operations["createDeploymentTarget"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/deployment-targets/{deploymentTargetId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 查询部署目标 */
        get: operations["getDeploymentTarget"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/deployment-targets/{deploymentTargetId}/releases": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 创建发布并接纳异步操作 */
        post: operations["createRelease"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/deployment-targets/{deploymentTargetId}/runtime-snapshot": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 从 Kubernetes 查询部署目标的当前运行状态 */
        get: operations["getRuntimeSnapshot"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/releases/{releaseId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 查询发布 */
        get: operations["getRelease"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/operations/{operationId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 查询异步操作 */
        get: operations["getOperation"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        CreateProjectRequest: {
            name: string;
            slug: string;
        };
        Project: {
            /** Format: uuid */
            id: string;
            name: string;
            slug: string;
            createdBy: string;
            /** Format: date-time */
            createdAt: string;
        };
        CreateApplicationRequest: {
            name: string;
            slug: string;
        };
        Application: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            projectId: string;
            name: string;
            slug: string;
            createdBy: string;
            /** Format: date-time */
            createdAt: string;
        };
        CreateDeploymentTargetRequest: {
            /** @enum {string} */
            stage: "development";
            replicas: number;
            containerPort: number;
        };
        DeploymentTarget: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            applicationId: string;
            /** @enum {string} */
            stage: "development";
            clusterRef: string;
            namespace: string;
            replicas: number;
            containerPort: number;
            createdBy: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        CreateReleaseRequest: {
            /** @description 包含 sha256 Digest 的不可变 OCI 镜像引用。 */
            imageReference: string;
        };
        ReleaseTargetSnapshot: {
            /** Format: uuid */
            projectId: string;
            /** Format: uuid */
            applicationId: string;
            /** @enum {string} */
            stage: "development";
            clusterRef: string;
            namespace: string;
            replicas: number;
            containerPort: number;
        };
        Release: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            deploymentTargetId: string;
            imageReference: string;
            targetSnapshot: components["schemas"]["ReleaseTargetSnapshot"];
            createdBy: string;
            /** Format: date-time */
            createdAt: string;
        };
        Operation: {
            /** Format: uuid */
            id: string;
            /** @enum {string} */
            type: "release.deploy";
            /** Format: uuid */
            releaseId: string;
            createdBy: string;
            idempotencyKey: string;
            /** @enum {string} */
            status: "pending" | "running" | "succeeded" | "failed";
            attemptCount: number;
            errorCategory?: string;
            errorSummary?: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
            /** Format: date-time */
            startedAt?: string;
            /** Format: date-time */
            finishedAt?: string;
            attempts: components["schemas"]["OperationAttempt"][];
        };
        OperationAttempt: {
            /** Format: uuid */
            id: string;
            number: number;
            workerId: string;
            /** @enum {string} */
            status: "running" | "succeeded" | "failed";
            errorCategory?: string;
            errorSummary?: string;
            /** Format: date-time */
            startedAt: string;
            /** Format: date-time */
            finishedAt?: string;
        };
        RuntimeSnapshot: {
            /** Format: uuid */
            deploymentTargetId: string;
            /** @enum {string} */
            source: "kubernetes";
            /** Format: date-time */
            observedAt: string;
            /** @enum {string} */
            freshness: "fresh" | "unavailable";
            deploymentName: string;
            deploymentExists: boolean;
            /** Format: uuid */
            releaseId?: string;
            desiredReplicas: number;
            updatedReplicas: number;
            readyReplicas: number;
            availableReplicas: number;
            conditions: components["schemas"]["RuntimeCondition"][];
            pods: components["schemas"]["RuntimePod"][];
            errorCategory?: string;
        };
        RuntimeCondition: {
            type: string;
            status: string;
            reason: string;
            message: string;
        };
        RuntimePod: {
            name: string;
            phase: string;
            ready: boolean;
            reason: string;
        };
        ReleaseAcceptance: {
            release: components["schemas"]["Release"];
            operation: components["schemas"]["Operation"];
        };
        Error: {
            code: string;
            message: string;
        };
    };
    responses: never;
    parameters: {
        /** @description 当前操作者与写操作范围内的幂等标识。 */
        IdempotencyKey: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    createProject: {
        parameters: {
            query?: never;
            header: {
                /** @description 当前操作者与写操作范围内的幂等标识。 */
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateProjectRequest"];
            };
        };
        responses: {
            /** @description 项目已创建 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Project"];
                };
            };
            /** @description 幂等键已经用于不同请求 */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description 请求失败 */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getProject: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 项目详情 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Project"];
                };
            };
            /** @description 项目不存在 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description 请求失败 */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    createApplication: {
        parameters: {
            query?: never;
            header: {
                /** @description 当前操作者与写操作范围内的幂等标识。 */
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                projectId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateApplicationRequest"];
            };
        };
        responses: {
            /** @description 应用已创建 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Application"];
                };
            };
            /** @description 项目不存在 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description 幂等键已经用于不同请求 */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description 请求失败 */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getApplication: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                applicationId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 应用详情 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Application"];
                };
            };
            /** @description 应用不存在 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description 请求失败 */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    createDeploymentTarget: {
        parameters: {
            query?: never;
            header: {
                /** @description 当前操作者与写操作范围内的幂等标识。 */
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                applicationId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateDeploymentTargetRequest"];
            };
        };
        responses: {
            /** @description 部署目标已创建 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeploymentTarget"];
                };
            };
            /** @description 应用不存在 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description 幂等键已经用于不同请求 */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description 请求失败 */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getDeploymentTarget: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                deploymentTargetId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 部署目标详情 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeploymentTarget"];
                };
            };
            /** @description 部署目标不存在 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description 请求失败 */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    createRelease: {
        parameters: {
            query?: never;
            header: {
                /** @description 当前操作者与写操作范围内的幂等标识。 */
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                deploymentTargetId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateReleaseRequest"];
            };
        };
        responses: {
            /** @description 发布与待处理操作已原子创建 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReleaseAcceptance"];
                };
            };
            /** @description 镜像引用不是有效的不可变 OCI 引用 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description 部署目标不存在 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description 幂等键已经用于不同请求 */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description 请求失败 */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getRuntimeSnapshot: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                deploymentTargetId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Kubernetes 运行时快照；不可访问时 freshness 为 unavailable */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RuntimeSnapshot"];
                };
            };
            /** @description 部署目标不存在 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description 请求失败 */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getRelease: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                releaseId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 发布详情 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Release"];
                };
            };
            /** @description 发布不存在 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description 请求失败 */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getOperation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                operationId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 操作详情 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Operation"];
                };
            };
            /** @description 操作不存在 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description 请求失败 */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
}
