/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 创建项目 */
        post: operations["createProject"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{projectId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 查询项目 */
        get: operations["getProject"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{projectId}/members": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 查询项目成员 */
        get: operations["listProjectMembers"];
        put?: never;
        /** 添加项目成员 */
        post: operations["addProjectMember"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{projectId}/members/{actorId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** 修改项目成员角色 */
        put: operations["updateProjectMember"];
        post?: never;
        /** 移除项目成员 */
        delete: operations["removeProjectMember"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{projectId}/applications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 创建应用 */
        post: operations["createApplication"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/applications/{applicationId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 查询应用 */
        get: operations["getApplication"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/applications/{applicationId}/deployment-targets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 创建部署目标 */
        post: operations["createDeploymentTarget"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/deployment-targets/{deploymentTargetId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 查询部署目标 */
        get: operations["getDeploymentTarget"];
        /** 更新部署目标的可变期望配置 */
        put: operations["updateDeploymentTarget"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/deployment-targets/{deploymentTargetId}/releases": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 分页查询部署目标的发布历史 */
        get: operations["listReleaseHistory"];
        put?: never;
        /** 创建发布并接纳异步操作 */
        post: operations["createRelease"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/releases/{releaseId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 查询发布 */
        get: operations["getRelease"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/releases/{releaseId}/diagnostics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 查询 Release 的控制面与 Kubernetes 诊断证据 */
        get: operations["getReleaseDiagnostics"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/releases/{releaseId}/runtime-logs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 读取属于指定 Release 的有界运行日志摘录 */
        get: operations["getReleaseRuntimeLogs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/releases/{releaseId}/rollback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 从历史不可变快照创建回滚发布 */
        post: operations["rollbackRelease"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/operations/{operationId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 查询异步操作 */
        get: operations["getOperation"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/operations/{operationId}/retry": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 重新排队一个确定失败或已安全确认的操作 */
        post: operations["retryOperation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/operations/{operationId}/reconcile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 只读核验需要人工关注的操作 */
        post: operations["reconcileOperation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/operations/{operationId}/fail": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 人工结束无法自动判断的操作 */
        post: operations["forceFailOperation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/operations/{operationId}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 取消排队中或运行中的操作 */
        post: operations["cancelOperation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        CreateProjectRequest: {
            name: string;
            slug: string;
        };
        Project: {
            /** Format: uuid */
            id: string;
            name: string;
            slug: string;
            createdBy: string;
            /** Format: date-time */
            createdAt: string;
        };
        AddProjectMemberRequest: {
            actorId: string;
            role: components["schemas"]["ProjectRole"];
        };
        UpdateProjectMemberRequest: {
            role: components["schemas"]["ProjectRole"];
        };
        /** @enum {string} */
        ProjectRole: "owner" | "developer" | "viewer";
        ProjectMember: {
            /** Format: uuid */
            projectId: string;
            actorId: string;
            role: components["schemas"]["ProjectRole"];
            createdBy: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        CreateApplicationRequest: {
            name: string;
            slug: string;
        };
        Application: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            projectId: string;
            name: string;
            slug: string;
            createdBy: string;
            /** Format: date-time */
            createdAt: string;
        };
        CreateDeploymentTargetRequest: {
            /** @enum {string} */
            stage: "development";
            replicas: number;
            containerPort: number;
        };
        UpdateDeploymentTargetRequest: {
            /** @enum {string} */
            stage: "development";
            replicas: number;
            containerPort: number;
        };
        DeploymentTarget: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            applicationId: string;
            /** @enum {string} */
            stage: "development";
            clusterRef: string;
            namespace: string;
            replicas: number;
            containerPort: number;
            createdBy: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        CreateReleaseRequest: {
            /** @description 包含 sha256 Digest 的不可变 OCI 镜像引用。 */
            imageReference: string;
        };
        ReleaseTargetSnapshot: {
            /** Format: uuid */
            projectId: string;
            /** Format: uuid */
            applicationId: string;
            /** @enum {string} */
            stage: "development";
            clusterRef: string;
            namespace: string;
            replicas: number;
            containerPort: number;
        };
        Release: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            deploymentTargetId: string;
            imageReference: string;
            targetSnapshot: components["schemas"]["ReleaseTargetSnapshot"];
            /** Format: uuid */
            rollbackOfReleaseId?: string;
            createdBy: string;
            /** Format: date-time */
            createdAt: string;
        };
        ReleaseHistoryPage: {
            items: components["schemas"]["ReleaseHistoryItem"][];
            nextCursor?: string;
        };
        ReleaseHistoryItem: {
            release: components["schemas"]["Release"];
            operation: components["schemas"]["OperationSummary"];
        };
        OperationSummary: {
            /** Format: uuid */
            id: string;
            /** @enum {string} */
            status: "pending" | "running" | "cancel_requested" | "succeeded" | "failed" | "canceled" | "attention_required";
            attemptCount: number;
            errorCode?: string;
            errorSummary?: string;
            /** Format: date-time */
            queuedAt: string;
            /** Format: date-time */
            startedAt?: string;
            /** Format: date-time */
            finishedAt?: string;
        };
        SnapshotDifference: {
            field: string;
            releaseValue: string;
            currentValue: string;
        };
        AuditRecord: {
            /** Format: uuid */
            id: string;
            actorId: string;
            /** @enum {string} */
            actorKind: "user" | "system";
            action: string;
            targetType: string;
            /** Format: uuid */
            targetId: string;
            summary: {
                [key: string]: unknown;
            };
            /** Format: date-time */
            createdAt: string;
        };
        ReleaseDetail: {
            release: components["schemas"]["Release"];
            snapshotDifferences: components["schemas"]["SnapshotDifference"][];
            operation: components["schemas"]["Operation"];
            auditTimeline: components["schemas"]["AuditRecord"][];
        };
        /** @enum {string} */
        RetryDisposition: "retryable" | "non_retryable" | "unknown_outcome";
        ForceFailOperationRequest: {
            reason: string;
        };
        Operation: {
            /** Format: uuid */
            id: string;
            /** @enum {string} */
            type: "release.deploy";
            /** Format: uuid */
            releaseId: string;
            /** Format: uuid */
            deploymentTargetId: string;
            createdBy: string;
            idempotencyKey: string;
            /** @enum {string} */
            status: "pending" | "running" | "cancel_requested" | "succeeded" | "failed" | "canceled" | "attention_required";
            attemptCount: number;
            automaticRetryCount: number;
            recoveryRequired: boolean;
            errorCode?: string;
            errorSummary?: string;
            retryDisposition?: components["schemas"]["RetryDisposition"];
            /** Format: date-time */
            queuedAt: string;
            /** Format: date-time */
            availableAt: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
            /** Format: date-time */
            startedAt?: string;
            /** Format: date-time */
            finishedAt?: string;
            attempts: components["schemas"]["OperationAttempt"][];
        };
        OperationAttempt: {
            /** Format: uuid */
            id: string;
            number: number;
            workerId: string;
            /** @enum {string} */
            status: "running" | "succeeded" | "failed" | "canceled" | "outcome_unknown";
            errorCode?: string;
            errorSummary?: string;
            retryDisposition?: components["schemas"]["RetryDisposition"];
            /** Format: date-time */
            startedAt: string;
            /** Format: date-time */
            finishedAt?: string;
        };
        ReleaseDiagnosticReport: {
            release: components["schemas"]["Release"];
            operation: components["schemas"]["Operation"];
            targetDifferences: components["schemas"]["SnapshotDifference"][];
            /** @enum {string} */
            runtimeReleaseRelation: "matches" | "different" | "absent" | "unknown";
            workloadObservation: components["schemas"]["WorkloadObservation"];
            eventObservation: components["schemas"]["EventObservation"];
            signals: components["schemas"]["DiagnosticSignal"][];
            /** Format: date-time */
            generatedAt: string;
        };
        ObservationMetadata: {
            /** @enum {string} */
            source: "kubernetes";
            /** Format: date-time */
            observedAt: string;
            /** @enum {string} */
            status: "complete" | "partial" | "unavailable";
            errorCategories: string[];
        };
        WorkloadObservation: {
            metadata: components["schemas"]["ObservationMetadata"];
            deployment?: components["schemas"]["DiagnosticDeployment"];
            service?: components["schemas"]["DiagnosticService"];
            pods: components["schemas"]["DiagnosticPod"][];
        };
        DiagnosticDeployment: {
            name: string;
            uid: string;
            ownershipMatches: boolean;
            /** Format: uuid */
            releaseId?: string;
            /** Format: int64 */
            generation: number;
            /** Format: int64 */
            observedGeneration: number;
            desiredReplicas: number;
            updatedReplicas: number;
            readyReplicas: number;
            availableReplicas: number;
            conditions: components["schemas"]["DiagnosticCondition"][];
        };
        DiagnosticCondition: {
            type: string;
            status: string;
            reason: string;
            message: string;
        };
        DiagnosticService: {
            name: string;
            uid: string;
            ownershipMatches: boolean;
            ports: components["schemas"]["DiagnosticServicePort"][];
        };
        DiagnosticServicePort: {
            name: string;
            protocol: string;
            port: number;
        };
        DiagnosticPod: {
            name: string;
            uid: string;
            /** Format: date-time */
            createdAt: string;
            phase: string;
            ready: boolean;
            reason: string;
            containers: components["schemas"]["DiagnosticContainer"][];
        };
        DiagnosticContainer: {
            name: string;
            ready: boolean;
            restartCount: number;
            /** @enum {string} */
            state: "waiting" | "running" | "terminated" | "unknown";
            reason: string;
            exitCode?: number;
            message: string;
            /** Format: date-time */
            startedAt?: string;
            /** Format: date-time */
            finishedAt?: string;
            previousTermination?: components["schemas"]["DiagnosticTermination"];
        };
        DiagnosticTermination: {
            reason: string;
            exitCode: number;
            message: string;
            /** Format: date-time */
            startedAt: string;
            /** Format: date-time */
            finishedAt: string;
        };
        EventObservation: {
            metadata: components["schemas"]["ObservationMetadata"];
            items: components["schemas"]["DiagnosticEvent"][];
        };
        DiagnosticEvent: {
            uid: string;
            type: string;
            reason: string;
            count: number;
            /** Format: date-time */
            firstSeen: string;
            /** Format: date-time */
            lastSeen: string;
            resourceKind: string;
            resourceName: string;
            resourceUid: string;
            message: string;
        };
        DiagnosticSignal: {
            /** @enum {string} */
            code: "operation_attention_required" | "operation_failed" | "runtime_observation_unavailable" | "deployment_missing" | "runtime_release_different" | "resource_ownership_conflict" | "rollout_incomplete" | "pod_waiting" | "pod_restarting" | "warning_event_observed";
            /** @enum {string} */
            severity: "error" | "warning" | "info";
            summary: string;
            evidenceRefs: components["schemas"]["DiagnosticEvidenceReference"][];
        };
        DiagnosticEvidenceReference: {
            source: string;
            kind: string;
            id: string;
        };
        RuntimeLogExcerpt: {
            /** @enum {string} */
            source: "kubernetes";
            /** Format: date-time */
            observedAt: string;
            /** Format: uuid */
            releaseId: string;
            podName: string;
            container: string;
            tailLines: number;
            previous: boolean;
            /** @description 已脱敏且 UTF-8 编码不超过 128 KiB 的一次性日志摘录。 */
            content: string;
            truncated: boolean;
        };
        ReleaseAcceptance: {
            release: components["schemas"]["Release"];
            operation: components["schemas"]["Operation"];
        };
        Error: {
            code: string;
            message: string;
        };
    };
    responses: never;
    parameters: {
        /** @description 当前操作者与写操作范围内的幂等标识。 */
        IdempotencyKey: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    createProject: {
        parameters: {
            query?: never;
            header: {
                /** @description 当前操作者与写操作范围内的幂等标识。 */
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateProjectRequest"];
            };
        };
        responses: {
            /** @description 项目已创建 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Project"];
                };
            };
            /** @description 幂等键已经用于不同请求 */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description 请求失败 */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getProject: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 项目详情 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Project"];
                };
            };
            /** @description 项目不存在 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description 请求失败 */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    listProjectMembers: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 项目成员列表 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectMember"][];
                };
            };
            /** @description 项目不存在或当前操作者不是项目成员 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description 请求失败 */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    addProjectMember: {
        parameters: {
            query?: never;
            header: {
                /** @description 当前操作者与写操作范围内的幂等标识。 */
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                projectId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddProjectMemberRequest"];
            };
        };
        responses: {
            /** @description 项目成员已添加 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectMember"];
                };
            };
            /** @description Actor ID 或项目角色无效 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description 当前项目角色不能管理成员 */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description 项目不存在或当前操作者不是项目成员 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description 成员已经存在或幂等键冲突 */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description 请求失败 */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    updateProjectMember: {
        parameters: {
            query?: never;
            header: {
                /** @description 当前操作者与写操作范围内的幂等标识。 */
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                projectId: string;
                actorId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateProjectMemberRequest"];
            };
        };
        responses: {
            /** @description 项目成员角色已修改 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectMember"];
                };
            };
            /** @description Actor ID 或项目角色无效 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description 当前项目角色不能管理成员 */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description 项目或成员不存在，或者当前操作者不是项目成员 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description 操作会移除最后一个 owner，或幂等键冲突 */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description 请求失败 */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    removeProjectMember: {
        parameters: {
            query?: never;
            header: {
                /** @description 当前操作者与写操作范围内的幂等标识。 */
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                projectId: string;
                actorId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 已移除的项目成员 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectMember"];
                };
            };
            /** @description Actor ID 无效 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description 当前项目角色不能管理成员 */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description 项目或成员不存在，或者当前操作者不是项目成员 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description 操作会移除最后一个 owner，或幂等键冲突 */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description 请求失败 */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    createApplication: {
        parameters: {
            query?: never;
            header: {
                /** @description 当前操作者与写操作范围内的幂等标识。 */
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                projectId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateApplicationRequest"];
            };
        };
        responses: {
            /** @description 应用已创建 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Application"];
                };
            };
            /** @description 当前项目角色不能创建应用 */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description 项目不存在 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description 幂等键已经用于不同请求 */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description 请求失败 */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getApplication: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                applicationId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 应用详情 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Application"];
                };
            };
            /** @description 应用不存在 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description 请求失败 */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    createDeploymentTarget: {
        parameters: {
            query?: never;
            header: {
                /** @description 当前操作者与写操作范围内的幂等标识。 */
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                applicationId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateDeploymentTargetRequest"];
            };
        };
        responses: {
            /** @description 部署目标已创建 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeploymentTarget"];
                };
            };
            /** @description 当前项目角色不能创建部署目标 */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description 应用不存在 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description 幂等键已经用于不同请求 */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description 请求失败 */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getDeploymentTarget: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                deploymentTargetId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 部署目标详情 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeploymentTarget"];
                };
            };
            /** @description 部署目标不存在 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description 请求失败 */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    updateDeploymentTarget: {
        parameters: {
            query?: never;
            header: {
                /** @description 当前操作者与写操作范围内的幂等标识。 */
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                deploymentTargetId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateDeploymentTargetRequest"];
            };
        };
        responses: {
            /** @description 部署目标已更新 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeploymentTarget"];
                };
            };
            /** @description 当前项目角色不能修改部署目标 */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description 部署目标不存在 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description 幂等键已经用于不同请求 */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description 请求失败 */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    listReleaseHistory: {
        parameters: {
            query?: {
                limit?: number;
                cursor?: string;
            };
            header?: never;
            path: {
                deploymentTargetId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 按创建时间和标识倒序排列的发布历史 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReleaseHistoryPage"];
                };
            };
            /** @description 分页游标无效 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description 部署目标不存在或当前操作者不是项目成员 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description 请求失败 */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    createRelease: {
        parameters: {
            query?: never;
            header: {
                /** @description 当前操作者与写操作范围内的幂等标识。 */
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                deploymentTargetId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateReleaseRequest"];
            };
        };
        responses: {
            /** @description 发布与待处理操作已原子创建 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReleaseAcceptance"];
                };
            };
            /** @description 镜像引用不是有效的不可变 OCI 引用 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description 当前项目角色不能创建发布 */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description 部署目标不存在 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description 幂等键已经用于不同请求 */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description 请求失败 */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getRelease: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                releaseId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 发布详情 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReleaseDetail"];
                };
            };
            /** @description 发布不存在 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description 请求失败 */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getReleaseDiagnostics: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                releaseId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 诊断报告；Kubernetes 部分或全部不可用时仍返回已有证据 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReleaseDiagnosticReport"];
                };
            };
            /** @description Release 不存在或当前操作者不是项目成员 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description 请求失败 */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getReleaseRuntimeLogs: {
        parameters: {
            query: {
                podName: string;
                container: string;
                tailLines?: number;
                previous?: boolean;
            };
            header?: never;
            path: {
                releaseId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 已验证归属并完成脱敏的日志摘录 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RuntimeLogExcerpt"];
                };
            };
            /** @description 日志查询参数无效 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description 当前项目角色不能读取原始运行日志 */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Release、Pod 或 Container 不存在或不属于指定 Release */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Kubernetes 当前不可用 */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description 请求失败 */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    rollbackRelease: {
        parameters: {
            query?: never;
            header: {
                /** @description 当前操作者与写操作范围内的幂等标识。 */
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                releaseId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 回滚 Release 与待处理 Operation 已原子创建 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReleaseAcceptance"];
                };
            };
            /** @description 当前项目角色不能创建回滚 */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description 来源 Release 不存在或当前操作者不是项目成员 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description 幂等键已经用于不同请求 */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description 请求失败 */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getOperation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                operationId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 操作详情 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Operation"];
                };
            };
            /** @description 操作不存在 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description 请求失败 */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    retryOperation: {
        parameters: {
            query?: never;
            header: {
                /** @description 当前操作者与写操作范围内的幂等标识。 */
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                operationId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 原 Operation 已重新进入目标队尾 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Operation"];
                };
            };
            /** @description 当前项目角色不能重试操作 */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description 操作不存在或当前操作者不是项目成员 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description 当前状态不允许重试，或幂等键冲突 */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description 请求失败 */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    reconcileOperation: {
        parameters: {
            query?: never;
            header: {
                /** @description 当前操作者与写操作范围内的幂等标识。 */
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                operationId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 已根据 Kubernetes 当前事实更新操作结论 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Operation"];
                };
            };
            /** @description 当前项目角色不能核验操作 */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description 操作不存在或当前操作者不是项目成员 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description 当前状态不允许核验、外部事实仍不明确，或幂等键冲突 */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description 请求失败 */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    forceFailOperation: {
        parameters: {
            query?: never;
            header: {
                /** @description 当前操作者与写操作范围内的幂等标识。 */
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                operationId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ForceFailOperationRequest"];
            };
        };
        responses: {
            /** @description 操作已由项目 owner 标记为失败 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Operation"];
                };
            };
            /** @description 只有项目 owner 可以人工结束未知结果 */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description 操作不存在或当前操作者不是项目成员 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description 当前状态不允许人工结束，或幂等键冲突 */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description 请求失败 */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    cancelOperation: {
        parameters: {
            query?: never;
            header: {
                /** @description 当前操作者与写操作范围内的幂等标识。 */
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                operationId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 操作已取消或已记录取消请求 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Operation"];
                };
            };
            /** @description 当前项目角色不能取消操作 */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description 操作不存在或当前操作者不是项目成员 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description 当前状态不允许取消，或幂等键冲突 */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description 请求失败 */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
}
