// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/flate"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/gin-gonic/gin"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for CreateDeploymentTargetRequestStage.
const (
	CreateDeploymentTargetRequestStageDevelopment CreateDeploymentTargetRequestStage = "development"
)

// Valid indicates whether the value is a known member of the CreateDeploymentTargetRequestStage enum.
func (e CreateDeploymentTargetRequestStage) Valid() bool {
	switch e {
	case CreateDeploymentTargetRequestStageDevelopment:
		return true
	default:
		return false
	}
}

// Defines values for DeploymentTargetStage.
const (
	DeploymentTargetStageDevelopment DeploymentTargetStage = "development"
)

// Valid indicates whether the value is a known member of the DeploymentTargetStage enum.
func (e DeploymentTargetStage) Valid() bool {
	switch e {
	case DeploymentTargetStageDevelopment:
		return true
	default:
		return false
	}
}

// Defines values for OperationStatus.
const (
	OperationStatusFailed    OperationStatus = "failed"
	OperationStatusPending   OperationStatus = "pending"
	OperationStatusRunning   OperationStatus = "running"
	OperationStatusSucceeded OperationStatus = "succeeded"
)

// Valid indicates whether the value is a known member of the OperationStatus enum.
func (e OperationStatus) Valid() bool {
	switch e {
	case OperationStatusFailed:
		return true
	case OperationStatusPending:
		return true
	case OperationStatusRunning:
		return true
	case OperationStatusSucceeded:
		return true
	default:
		return false
	}
}

// Defines values for OperationType.
const (
	ReleaseDeploy OperationType = "release.deploy"
)

// Valid indicates whether the value is a known member of the OperationType enum.
func (e OperationType) Valid() bool {
	switch e {
	case ReleaseDeploy:
		return true
	default:
		return false
	}
}

// Defines values for OperationAttemptStatus.
const (
	OperationAttemptStatusFailed    OperationAttemptStatus = "failed"
	OperationAttemptStatusRunning   OperationAttemptStatus = "running"
	OperationAttemptStatusSucceeded OperationAttemptStatus = "succeeded"
)

// Valid indicates whether the value is a known member of the OperationAttemptStatus enum.
func (e OperationAttemptStatus) Valid() bool {
	switch e {
	case OperationAttemptStatusFailed:
		return true
	case OperationAttemptStatusRunning:
		return true
	case OperationAttemptStatusSucceeded:
		return true
	default:
		return false
	}
}

// Defines values for ProjectRole.
const (
	Developer ProjectRole = "developer"
	Owner     ProjectRole = "owner"
	Viewer    ProjectRole = "viewer"
)

// Valid indicates whether the value is a known member of the ProjectRole enum.
func (e ProjectRole) Valid() bool {
	switch e {
	case Developer:
		return true
	case Owner:
		return true
	case Viewer:
		return true
	default:
		return false
	}
}

// Defines values for ReleaseTargetSnapshotStage.
const (
	ReleaseTargetSnapshotStageDevelopment ReleaseTargetSnapshotStage = "development"
)

// Valid indicates whether the value is a known member of the ReleaseTargetSnapshotStage enum.
func (e ReleaseTargetSnapshotStage) Valid() bool {
	switch e {
	case ReleaseTargetSnapshotStageDevelopment:
		return true
	default:
		return false
	}
}

// Defines values for RuntimeSnapshotFreshness.
const (
	Fresh       RuntimeSnapshotFreshness = "fresh"
	Unavailable RuntimeSnapshotFreshness = "unavailable"
)

// Valid indicates whether the value is a known member of the RuntimeSnapshotFreshness enum.
func (e RuntimeSnapshotFreshness) Valid() bool {
	switch e {
	case Fresh:
		return true
	case Unavailable:
		return true
	default:
		return false
	}
}

// Defines values for RuntimeSnapshotSource.
const (
	Kubernetes RuntimeSnapshotSource = "kubernetes"
)

// Valid indicates whether the value is a known member of the RuntimeSnapshotSource enum.
func (e RuntimeSnapshotSource) Valid() bool {
	switch e {
	case Kubernetes:
		return true
	default:
		return false
	}
}

// Defines values for UpdateDeploymentTargetRequestStage.
const (
	UpdateDeploymentTargetRequestStageDevelopment UpdateDeploymentTargetRequestStage = "development"
)

// Valid indicates whether the value is a known member of the UpdateDeploymentTargetRequestStage enum.
func (e UpdateDeploymentTargetRequestStage) Valid() bool {
	switch e {
	case UpdateDeploymentTargetRequestStageDevelopment:
		return true
	default:
		return false
	}
}

// AddProjectMemberRequest defines model for AddProjectMemberRequest.
type AddProjectMemberRequest struct {
	ActorId string      `json:"actorId"`
	Role    ProjectRole `json:"role"`
}

// Application defines model for Application.
type Application struct {
	CreatedAt time.Time          `json:"createdAt"`
	CreatedBy string             `json:"createdBy"`
	Id        openapi_types.UUID `json:"id"`
	Name      string             `json:"name"`
	ProjectId openapi_types.UUID `json:"projectId"`
	Slug      string             `json:"slug"`
}

// CreateApplicationRequest defines model for CreateApplicationRequest.
type CreateApplicationRequest struct {
	Name string `json:"name"`
	Slug string `json:"slug"`
}

// CreateDeploymentTargetRequest defines model for CreateDeploymentTargetRequest.
type CreateDeploymentTargetRequest struct {
	ContainerPort int                                `json:"containerPort"`
	Replicas      int                                `json:"replicas"`
	Stage         CreateDeploymentTargetRequestStage `json:"stage"`
}

// CreateDeploymentTargetRequestStage defines model for CreateDeploymentTargetRequest.Stage.
type CreateDeploymentTargetRequestStage string

// CreateProjectRequest defines model for CreateProjectRequest.
type CreateProjectRequest struct {
	Name string `json:"name"`
	Slug string `json:"slug"`
}

// CreateReleaseRequest defines model for CreateReleaseRequest.
type CreateReleaseRequest struct {
	// ImageReference 包含 sha256 Digest 的不可变 OCI 镜像引用。
	ImageReference string `json:"imageReference"`
}

// DeploymentTarget defines model for DeploymentTarget.
type DeploymentTarget struct {
	ApplicationId openapi_types.UUID    `json:"applicationId"`
	ClusterRef    string                `json:"clusterRef"`
	ContainerPort int                   `json:"containerPort"`
	CreatedAt     time.Time             `json:"createdAt"`
	CreatedBy     string                `json:"createdBy"`
	Id            openapi_types.UUID    `json:"id"`
	Namespace     string                `json:"namespace"`
	Replicas      int                   `json:"replicas"`
	Stage         DeploymentTargetStage `json:"stage"`
	UpdatedAt     time.Time             `json:"updatedAt"`
}

// DeploymentTargetStage defines model for DeploymentTarget.Stage.
type DeploymentTargetStage string

// Error defines model for Error.
type Error struct {
	Code    string `json:"code"`
	Message string `json:"message"`
}

// Operation defines model for Operation.
type Operation struct {
	AttemptCount   int                `json:"attemptCount"`
	Attempts       []OperationAttempt `json:"attempts"`
	CreatedAt      time.Time          `json:"createdAt"`
	CreatedBy      string             `json:"createdBy"`
	ErrorCategory  *string            `json:"errorCategory,omitempty"`
	ErrorSummary   *string            `json:"errorSummary,omitempty"`
	FinishedAt     *time.Time         `json:"finishedAt,omitempty"`
	Id             openapi_types.UUID `json:"id"`
	IdempotencyKey string             `json:"idempotencyKey"`
	ReleaseId      openapi_types.UUID `json:"releaseId"`
	StartedAt      *time.Time         `json:"startedAt,omitempty"`
	Status         OperationStatus    `json:"status"`
	Type           OperationType      `json:"type"`
	UpdatedAt      time.Time          `json:"updatedAt"`
}

// OperationStatus defines model for Operation.Status.
type OperationStatus string

// OperationType defines model for Operation.Type.
type OperationType string

// OperationAttempt defines model for OperationAttempt.
type OperationAttempt struct {
	ErrorCategory *string                `json:"errorCategory,omitempty"`
	ErrorSummary  *string                `json:"errorSummary,omitempty"`
	FinishedAt    *time.Time             `json:"finishedAt,omitempty"`
	Id            openapi_types.UUID     `json:"id"`
	Number        int                    `json:"number"`
	StartedAt     time.Time              `json:"startedAt"`
	Status        OperationAttemptStatus `json:"status"`
	WorkerId      string                 `json:"workerId"`
}

// OperationAttemptStatus defines model for OperationAttempt.Status.
type OperationAttemptStatus string

// Project defines model for Project.
type Project struct {
	CreatedAt time.Time          `json:"createdAt"`
	CreatedBy string             `json:"createdBy"`
	Id        openapi_types.UUID `json:"id"`
	Name      string             `json:"name"`
	Slug      string             `json:"slug"`
}

// ProjectMember defines model for ProjectMember.
type ProjectMember struct {
	ActorId   string             `json:"actorId"`
	CreatedAt time.Time          `json:"createdAt"`
	CreatedBy string             `json:"createdBy"`
	ProjectId openapi_types.UUID `json:"projectId"`
	Role      ProjectRole        `json:"role"`
	UpdatedAt time.Time          `json:"updatedAt"`
}

// ProjectRole defines model for ProjectRole.
type ProjectRole string

// Release defines model for Release.
type Release struct {
	CreatedAt          time.Time             `json:"createdAt"`
	CreatedBy          string                `json:"createdBy"`
	DeploymentTargetId openapi_types.UUID    `json:"deploymentTargetId"`
	Id                 openapi_types.UUID    `json:"id"`
	ImageReference     string                `json:"imageReference"`
	TargetSnapshot     ReleaseTargetSnapshot `json:"targetSnapshot"`
}

// ReleaseAcceptance defines model for ReleaseAcceptance.
type ReleaseAcceptance struct {
	Operation Operation `json:"operation"`
	Release   Release   `json:"release"`
}

// ReleaseTargetSnapshot defines model for ReleaseTargetSnapshot.
type ReleaseTargetSnapshot struct {
	ApplicationId openapi_types.UUID         `json:"applicationId"`
	ClusterRef    string                     `json:"clusterRef"`
	ContainerPort int                        `json:"containerPort"`
	Namespace     string                     `json:"namespace"`
	ProjectId     openapi_types.UUID         `json:"projectId"`
	Replicas      int                        `json:"replicas"`
	Stage         ReleaseTargetSnapshotStage `json:"stage"`
}

// ReleaseTargetSnapshotStage defines model for ReleaseTargetSnapshot.Stage.
type ReleaseTargetSnapshotStage string

// RuntimeCondition defines model for RuntimeCondition.
type RuntimeCondition struct {
	Message string `json:"message"`
	Reason  string `json:"reason"`
	Status  string `json:"status"`
	Type    string `json:"type"`
}

// RuntimePod defines model for RuntimePod.
type RuntimePod struct {
	Name   string `json:"name"`
	Phase  string `json:"phase"`
	Ready  bool   `json:"ready"`
	Reason string `json:"reason"`
}

// RuntimeSnapshot defines model for RuntimeSnapshot.
type RuntimeSnapshot struct {
	AvailableReplicas  int                      `json:"availableReplicas"`
	Conditions         []RuntimeCondition       `json:"conditions"`
	DeploymentExists   bool                     `json:"deploymentExists"`
	DeploymentName     string                   `json:"deploymentName"`
	DeploymentTargetId openapi_types.UUID       `json:"deploymentTargetId"`
	DesiredReplicas    int                      `json:"desiredReplicas"`
	ErrorCategory      *string                  `json:"errorCategory,omitempty"`
	Freshness          RuntimeSnapshotFreshness `json:"freshness"`
	ObservedAt         time.Time                `json:"observedAt"`
	Pods               []RuntimePod             `json:"pods"`
	ReadyReplicas      int                      `json:"readyReplicas"`
	ReleaseId          *openapi_types.UUID      `json:"releaseId,omitempty"`
	Source             RuntimeSnapshotSource    `json:"source"`
	UpdatedReplicas    int                      `json:"updatedReplicas"`
}

// RuntimeSnapshotFreshness defines model for RuntimeSnapshot.Freshness.
type RuntimeSnapshotFreshness string

// RuntimeSnapshotSource defines model for RuntimeSnapshot.Source.
type RuntimeSnapshotSource string

// UpdateDeploymentTargetRequest defines model for UpdateDeploymentTargetRequest.
type UpdateDeploymentTargetRequest struct {
	ContainerPort int                                `json:"containerPort"`
	Replicas      int                                `json:"replicas"`
	Stage         UpdateDeploymentTargetRequestStage `json:"stage"`
}

// UpdateDeploymentTargetRequestStage defines model for UpdateDeploymentTargetRequest.Stage.
type UpdateDeploymentTargetRequestStage string

// UpdateProjectMemberRequest defines model for UpdateProjectMemberRequest.
type UpdateProjectMemberRequest struct {
	Role ProjectRole `json:"role"`
}

// IdempotencyKey defines model for IdempotencyKey.
type IdempotencyKey = string

// CreateDeploymentTargetParams defines parameters for CreateDeploymentTarget.
type CreateDeploymentTargetParams struct {
	// IdempotencyKey 当前操作者与写操作范围内的幂等标识。
	IdempotencyKey IdempotencyKey `json:"Idempotency-Key"`
}

// UpdateDeploymentTargetParams defines parameters for UpdateDeploymentTarget.
type UpdateDeploymentTargetParams struct {
	// IdempotencyKey 当前操作者与写操作范围内的幂等标识。
	IdempotencyKey IdempotencyKey `json:"Idempotency-Key"`
}

// CreateReleaseParams defines parameters for CreateRelease.
type CreateReleaseParams struct {
	// IdempotencyKey 当前操作者与写操作范围内的幂等标识。
	IdempotencyKey IdempotencyKey `json:"Idempotency-Key"`
}

// CreateProjectParams defines parameters for CreateProject.
type CreateProjectParams struct {
	// IdempotencyKey 当前操作者与写操作范围内的幂等标识。
	IdempotencyKey IdempotencyKey `json:"Idempotency-Key"`
}

// CreateApplicationParams defines parameters for CreateApplication.
type CreateApplicationParams struct {
	// IdempotencyKey 当前操作者与写操作范围内的幂等标识。
	IdempotencyKey IdempotencyKey `json:"Idempotency-Key"`
}

// AddProjectMemberParams defines parameters for AddProjectMember.
type AddProjectMemberParams struct {
	// IdempotencyKey 当前操作者与写操作范围内的幂等标识。
	IdempotencyKey IdempotencyKey `json:"Idempotency-Key"`
}

// RemoveProjectMemberParams defines parameters for RemoveProjectMember.
type RemoveProjectMemberParams struct {
	// IdempotencyKey 当前操作者与写操作范围内的幂等标识。
	IdempotencyKey IdempotencyKey `json:"Idempotency-Key"`
}

// UpdateProjectMemberParams defines parameters for UpdateProjectMember.
type UpdateProjectMemberParams struct {
	// IdempotencyKey 当前操作者与写操作范围内的幂等标识。
	IdempotencyKey IdempotencyKey `json:"Idempotency-Key"`
}

// CreateDeploymentTargetJSONRequestBody defines body for CreateDeploymentTarget for application/json ContentType.
type CreateDeploymentTargetJSONRequestBody = CreateDeploymentTargetRequest

// UpdateDeploymentTargetJSONRequestBody defines body for UpdateDeploymentTarget for application/json ContentType.
type UpdateDeploymentTargetJSONRequestBody = UpdateDeploymentTargetRequest

// CreateReleaseJSONRequestBody defines body for CreateRelease for application/json ContentType.
type CreateReleaseJSONRequestBody = CreateReleaseRequest

// CreateProjectJSONRequestBody defines body for CreateProject for application/json ContentType.
type CreateProjectJSONRequestBody = CreateProjectRequest

// CreateApplicationJSONRequestBody defines body for CreateApplication for application/json ContentType.
type CreateApplicationJSONRequestBody = CreateApplicationRequest

// AddProjectMemberJSONRequestBody defines body for AddProjectMember for application/json ContentType.
type AddProjectMemberJSONRequestBody = AddProjectMemberRequest

// UpdateProjectMemberJSONRequestBody defines body for UpdateProjectMember for application/json ContentType.
type UpdateProjectMemberJSONRequestBody = UpdateProjectMemberRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// GetApplication 查询应用
	// (GET /api/v1/applications/{applicationId})
	GetApplication(c *gin.Context, applicationId openapi_types.UUID)
	// CreateDeploymentTarget 创建部署目标
	// (POST /api/v1/applications/{applicationId}/deployment-targets)
	CreateDeploymentTarget(c *gin.Context, applicationId openapi_types.UUID, params CreateDeploymentTargetParams)
	// GetDeploymentTarget 查询部署目标
	// (GET /api/v1/deployment-targets/{deploymentTargetId})
	GetDeploymentTarget(c *gin.Context, deploymentTargetId openapi_types.UUID)
	// UpdateDeploymentTarget 更新部署目标的可变期望配置
	// (PUT /api/v1/deployment-targets/{deploymentTargetId})
	UpdateDeploymentTarget(c *gin.Context, deploymentTargetId openapi_types.UUID, params UpdateDeploymentTargetParams)
	// CreateRelease 创建发布并接纳异步操作
	// (POST /api/v1/deployment-targets/{deploymentTargetId}/releases)
	CreateRelease(c *gin.Context, deploymentTargetId openapi_types.UUID, params CreateReleaseParams)
	// GetRuntimeSnapshot 从 Kubernetes 查询部署目标的当前运行状态
	// (GET /api/v1/deployment-targets/{deploymentTargetId}/runtime-snapshot)
	GetRuntimeSnapshot(c *gin.Context, deploymentTargetId openapi_types.UUID)
	// GetOperation 查询异步操作
	// (GET /api/v1/operations/{operationId})
	GetOperation(c *gin.Context, operationId openapi_types.UUID)
	// CreateProject 创建项目
	// (POST /api/v1/projects)
	CreateProject(c *gin.Context, params CreateProjectParams)
	// GetProject 查询项目
	// (GET /api/v1/projects/{projectId})
	GetProject(c *gin.Context, projectId openapi_types.UUID)
	// CreateApplication 创建应用
	// (POST /api/v1/projects/{projectId}/applications)
	CreateApplication(c *gin.Context, projectId openapi_types.UUID, params CreateApplicationParams)
	// ListProjectMembers 查询项目成员
	// (GET /api/v1/projects/{projectId}/members)
	ListProjectMembers(c *gin.Context, projectId openapi_types.UUID)
	// AddProjectMember 添加项目成员
	// (POST /api/v1/projects/{projectId}/members)
	AddProjectMember(c *gin.Context, projectId openapi_types.UUID, params AddProjectMemberParams)
	// RemoveProjectMember 移除项目成员
	// (DELETE /api/v1/projects/{projectId}/members/{actorId})
	RemoveProjectMember(c *gin.Context, projectId openapi_types.UUID, actorId string, params RemoveProjectMemberParams)
	// UpdateProjectMember 修改项目成员角色
	// (PUT /api/v1/projects/{projectId}/members/{actorId})
	UpdateProjectMember(c *gin.Context, projectId openapi_types.UUID, actorId string, params UpdateProjectMemberParams)
	// GetRelease 查询发布
	// (GET /api/v1/releases/{releaseId})
	GetRelease(c *gin.Context, releaseId openapi_types.UUID)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// GetApplication operation middleware
func (siw *ServerInterfaceWrapper) GetApplication(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "applicationId" -------------
	var applicationId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "applicationId", c.Param("applicationId"), &applicationId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter applicationId: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetApplication(c, applicationId)
}

// CreateDeploymentTarget operation middleware
func (siw *ServerInterfaceWrapper) CreateDeploymentTarget(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "applicationId" -------------
	var applicationId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "applicationId", c.Param("applicationId"), &applicationId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter applicationId: %w", err), http.StatusBadRequest)
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params CreateDeploymentTargetParams

	headers := c.Request.Header

	// ------------- Required header parameter "Idempotency-Key" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Idempotency-Key")]; found {
		var IdempotencyKey IdempotencyKey
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandler(c, fmt.Errorf("Expected one value for Idempotency-Key, got %d", n), http.StatusBadRequest)
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Idempotency-Key", valueList[0], &IdempotencyKey, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter Idempotency-Key: %w", err), http.StatusBadRequest)
			return
		}

		params.IdempotencyKey = IdempotencyKey

	} else {
		siw.ErrorHandler(c, fmt.Errorf("Header parameter Idempotency-Key is required, but not found"), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.CreateDeploymentTarget(c, applicationId, params)
}

// GetDeploymentTarget operation middleware
func (siw *ServerInterfaceWrapper) GetDeploymentTarget(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "deploymentTargetId" -------------
	var deploymentTargetId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "deploymentTargetId", c.Param("deploymentTargetId"), &deploymentTargetId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter deploymentTargetId: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetDeploymentTarget(c, deploymentTargetId)
}

// UpdateDeploymentTarget operation middleware
func (siw *ServerInterfaceWrapper) UpdateDeploymentTarget(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "deploymentTargetId" -------------
	var deploymentTargetId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "deploymentTargetId", c.Param("deploymentTargetId"), &deploymentTargetId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter deploymentTargetId: %w", err), http.StatusBadRequest)
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params UpdateDeploymentTargetParams

	headers := c.Request.Header

	// ------------- Required header parameter "Idempotency-Key" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Idempotency-Key")]; found {
		var IdempotencyKey IdempotencyKey
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandler(c, fmt.Errorf("Expected one value for Idempotency-Key, got %d", n), http.StatusBadRequest)
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Idempotency-Key", valueList[0], &IdempotencyKey, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter Idempotency-Key: %w", err), http.StatusBadRequest)
			return
		}

		params.IdempotencyKey = IdempotencyKey

	} else {
		siw.ErrorHandler(c, fmt.Errorf("Header parameter Idempotency-Key is required, but not found"), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.UpdateDeploymentTarget(c, deploymentTargetId, params)
}

// CreateRelease operation middleware
func (siw *ServerInterfaceWrapper) CreateRelease(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "deploymentTargetId" -------------
	var deploymentTargetId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "deploymentTargetId", c.Param("deploymentTargetId"), &deploymentTargetId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter deploymentTargetId: %w", err), http.StatusBadRequest)
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params CreateReleaseParams

	headers := c.Request.Header

	// ------------- Required header parameter "Idempotency-Key" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Idempotency-Key")]; found {
		var IdempotencyKey IdempotencyKey
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandler(c, fmt.Errorf("Expected one value for Idempotency-Key, got %d", n), http.StatusBadRequest)
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Idempotency-Key", valueList[0], &IdempotencyKey, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter Idempotency-Key: %w", err), http.StatusBadRequest)
			return
		}

		params.IdempotencyKey = IdempotencyKey

	} else {
		siw.ErrorHandler(c, fmt.Errorf("Header parameter Idempotency-Key is required, but not found"), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.CreateRelease(c, deploymentTargetId, params)
}

// GetRuntimeSnapshot operation middleware
func (siw *ServerInterfaceWrapper) GetRuntimeSnapshot(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "deploymentTargetId" -------------
	var deploymentTargetId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "deploymentTargetId", c.Param("deploymentTargetId"), &deploymentTargetId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter deploymentTargetId: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetRuntimeSnapshot(c, deploymentTargetId)
}

// GetOperation operation middleware
func (siw *ServerInterfaceWrapper) GetOperation(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "operationId" -------------
	var operationId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "operationId", c.Param("operationId"), &operationId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter operationId: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetOperation(c, operationId)
}

// CreateProject operation middleware
func (siw *ServerInterfaceWrapper) CreateProject(c *gin.Context) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params CreateProjectParams

	headers := c.Request.Header

	// ------------- Required header parameter "Idempotency-Key" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Idempotency-Key")]; found {
		var IdempotencyKey IdempotencyKey
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandler(c, fmt.Errorf("Expected one value for Idempotency-Key, got %d", n), http.StatusBadRequest)
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Idempotency-Key", valueList[0], &IdempotencyKey, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter Idempotency-Key: %w", err), http.StatusBadRequest)
			return
		}

		params.IdempotencyKey = IdempotencyKey

	} else {
		siw.ErrorHandler(c, fmt.Errorf("Header parameter Idempotency-Key is required, but not found"), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.CreateProject(c, params)
}

// GetProject operation middleware
func (siw *ServerInterfaceWrapper) GetProject(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "projectId" -------------
	var projectId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "projectId", c.Param("projectId"), &projectId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter projectId: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetProject(c, projectId)
}

// CreateApplication operation middleware
func (siw *ServerInterfaceWrapper) CreateApplication(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "projectId" -------------
	var projectId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "projectId", c.Param("projectId"), &projectId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter projectId: %w", err), http.StatusBadRequest)
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params CreateApplicationParams

	headers := c.Request.Header

	// ------------- Required header parameter "Idempotency-Key" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Idempotency-Key")]; found {
		var IdempotencyKey IdempotencyKey
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandler(c, fmt.Errorf("Expected one value for Idempotency-Key, got %d", n), http.StatusBadRequest)
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Idempotency-Key", valueList[0], &IdempotencyKey, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter Idempotency-Key: %w", err), http.StatusBadRequest)
			return
		}

		params.IdempotencyKey = IdempotencyKey

	} else {
		siw.ErrorHandler(c, fmt.Errorf("Header parameter Idempotency-Key is required, but not found"), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.CreateApplication(c, projectId, params)
}

// ListProjectMembers operation middleware
func (siw *ServerInterfaceWrapper) ListProjectMembers(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "projectId" -------------
	var projectId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "projectId", c.Param("projectId"), &projectId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter projectId: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListProjectMembers(c, projectId)
}

// AddProjectMember operation middleware
func (siw *ServerInterfaceWrapper) AddProjectMember(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "projectId" -------------
	var projectId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "projectId", c.Param("projectId"), &projectId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter projectId: %w", err), http.StatusBadRequest)
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params AddProjectMemberParams

	headers := c.Request.Header

	// ------------- Required header parameter "Idempotency-Key" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Idempotency-Key")]; found {
		var IdempotencyKey IdempotencyKey
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandler(c, fmt.Errorf("Expected one value for Idempotency-Key, got %d", n), http.StatusBadRequest)
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Idempotency-Key", valueList[0], &IdempotencyKey, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter Idempotency-Key: %w", err), http.StatusBadRequest)
			return
		}

		params.IdempotencyKey = IdempotencyKey

	} else {
		siw.ErrorHandler(c, fmt.Errorf("Header parameter Idempotency-Key is required, but not found"), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.AddProjectMember(c, projectId, params)
}

// RemoveProjectMember operation middleware
func (siw *ServerInterfaceWrapper) RemoveProjectMember(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "projectId" -------------
	var projectId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "projectId", c.Param("projectId"), &projectId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter projectId: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Path parameter "actorId" -------------
	var actorId string

	err = runtime.BindStyledParameterWithOptions("simple", "actorId", c.Param("actorId"), &actorId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter actorId: %w", err), http.StatusBadRequest)
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params RemoveProjectMemberParams

	headers := c.Request.Header

	// ------------- Required header parameter "Idempotency-Key" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Idempotency-Key")]; found {
		var IdempotencyKey IdempotencyKey
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandler(c, fmt.Errorf("Expected one value for Idempotency-Key, got %d", n), http.StatusBadRequest)
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Idempotency-Key", valueList[0], &IdempotencyKey, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter Idempotency-Key: %w", err), http.StatusBadRequest)
			return
		}

		params.IdempotencyKey = IdempotencyKey

	} else {
		siw.ErrorHandler(c, fmt.Errorf("Header parameter Idempotency-Key is required, but not found"), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.RemoveProjectMember(c, projectId, actorId, params)
}

// UpdateProjectMember operation middleware
func (siw *ServerInterfaceWrapper) UpdateProjectMember(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "projectId" -------------
	var projectId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "projectId", c.Param("projectId"), &projectId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter projectId: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Path parameter "actorId" -------------
	var actorId string

	err = runtime.BindStyledParameterWithOptions("simple", "actorId", c.Param("actorId"), &actorId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter actorId: %w", err), http.StatusBadRequest)
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params UpdateProjectMemberParams

	headers := c.Request.Header

	// ------------- Required header parameter "Idempotency-Key" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Idempotency-Key")]; found {
		var IdempotencyKey IdempotencyKey
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandler(c, fmt.Errorf("Expected one value for Idempotency-Key, got %d", n), http.StatusBadRequest)
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Idempotency-Key", valueList[0], &IdempotencyKey, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter Idempotency-Key: %w", err), http.StatusBadRequest)
			return
		}

		params.IdempotencyKey = IdempotencyKey

	} else {
		siw.ErrorHandler(c, fmt.Errorf("Header parameter Idempotency-Key is required, but not found"), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.UpdateProjectMember(c, projectId, actorId, params)
}

// GetRelease operation middleware
func (siw *ServerInterfaceWrapper) GetRelease(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "releaseId" -------------
	var releaseId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "releaseId", c.Param("releaseId"), &releaseId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter releaseId: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetRelease(c, releaseId)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.POST(options.BaseURL+"/api/v1/projects", wrapper.CreateProject)
	router.GET(options.BaseURL+"/api/v1/projects/:projectId", wrapper.GetProject)
	router.GET(options.BaseURL+"/api/v1/projects/:projectId/members", wrapper.ListProjectMembers)
	router.POST(options.BaseURL+"/api/v1/projects/:projectId/members", wrapper.AddProjectMember)
	router.DELETE(options.BaseURL+"/api/v1/projects/:projectId/members/:actorId", wrapper.RemoveProjectMember)
	router.PUT(options.BaseURL+"/api/v1/projects/:projectId/members/:actorId", wrapper.UpdateProjectMember)
	router.POST(options.BaseURL+"/api/v1/projects/:projectId/applications", wrapper.CreateApplication)
	router.GET(options.BaseURL+"/api/v1/applications/:applicationId", wrapper.GetApplication)
	router.POST(options.BaseURL+"/api/v1/applications/:applicationId/deployment-targets", wrapper.CreateDeploymentTarget)
	router.GET(options.BaseURL+"/api/v1/deployment-targets/:deploymentTargetId", wrapper.GetDeploymentTarget)
	router.PUT(options.BaseURL+"/api/v1/deployment-targets/:deploymentTargetId", wrapper.UpdateDeploymentTarget)
	router.POST(options.BaseURL+"/api/v1/deployment-targets/:deploymentTargetId/releases", wrapper.CreateRelease)
	router.GET(options.BaseURL+"/api/v1/deployment-targets/:deploymentTargetId/runtime-snapshot", wrapper.GetRuntimeSnapshot)
	router.GET(options.BaseURL+"/api/v1/releases/:releaseId", wrapper.GetRelease)
	router.GET(options.BaseURL+"/api/v1/operations/:operationId", wrapper.GetOperation)
}

type GetApplicationRequestObject struct {
	ApplicationId openapi_types.UUID `json:"applicationId"`
}

type GetApplicationResponseObject interface {
	VisitGetApplicationResponse(w http.ResponseWriter) error
}

type GetApplication200JSONResponse Application

func (response GetApplication200JSONResponse) VisitGetApplicationResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetApplication404JSONResponse Error

func (response GetApplication404JSONResponse) VisitGetApplicationResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type GetApplicationdefaultJSONResponse struct {
	Body       Error
	StatusCode int
}

func (response GetApplicationdefaultJSONResponse) VisitGetApplicationResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type CreateDeploymentTargetRequestObject struct {
	ApplicationId openapi_types.UUID `json:"applicationId"`
	Params        CreateDeploymentTargetParams
	Body          *CreateDeploymentTargetJSONRequestBody
}

type CreateDeploymentTargetResponseObject interface {
	VisitCreateDeploymentTargetResponse(w http.ResponseWriter) error
}

type CreateDeploymentTarget201JSONResponse DeploymentTarget

func (response CreateDeploymentTarget201JSONResponse) VisitCreateDeploymentTargetResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)
	_, err := buf.WriteTo(w)
	return err
}

type CreateDeploymentTarget403JSONResponse Error

func (response CreateDeploymentTarget403JSONResponse) VisitCreateDeploymentTargetResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type CreateDeploymentTarget404JSONResponse Error

func (response CreateDeploymentTarget404JSONResponse) VisitCreateDeploymentTargetResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type CreateDeploymentTarget409JSONResponse Error

func (response CreateDeploymentTarget409JSONResponse) VisitCreateDeploymentTargetResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)
	_, err := buf.WriteTo(w)
	return err
}

type CreateDeploymentTargetdefaultJSONResponse struct {
	Body       Error
	StatusCode int
}

func (response CreateDeploymentTargetdefaultJSONResponse) VisitCreateDeploymentTargetResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type GetDeploymentTargetRequestObject struct {
	DeploymentTargetId openapi_types.UUID `json:"deploymentTargetId"`
}

type GetDeploymentTargetResponseObject interface {
	VisitGetDeploymentTargetResponse(w http.ResponseWriter) error
}

type GetDeploymentTarget200JSONResponse DeploymentTarget

func (response GetDeploymentTarget200JSONResponse) VisitGetDeploymentTargetResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetDeploymentTarget404JSONResponse Error

func (response GetDeploymentTarget404JSONResponse) VisitGetDeploymentTargetResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type GetDeploymentTargetdefaultJSONResponse struct {
	Body       Error
	StatusCode int
}

func (response GetDeploymentTargetdefaultJSONResponse) VisitGetDeploymentTargetResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateDeploymentTargetRequestObject struct {
	DeploymentTargetId openapi_types.UUID `json:"deploymentTargetId"`
	Params             UpdateDeploymentTargetParams
	Body               *UpdateDeploymentTargetJSONRequestBody
}

type UpdateDeploymentTargetResponseObject interface {
	VisitUpdateDeploymentTargetResponse(w http.ResponseWriter) error
}

type UpdateDeploymentTarget200JSONResponse DeploymentTarget

func (response UpdateDeploymentTarget200JSONResponse) VisitUpdateDeploymentTargetResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateDeploymentTarget403JSONResponse Error

func (response UpdateDeploymentTarget403JSONResponse) VisitUpdateDeploymentTargetResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateDeploymentTarget404JSONResponse Error

func (response UpdateDeploymentTarget404JSONResponse) VisitUpdateDeploymentTargetResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateDeploymentTarget409JSONResponse Error

func (response UpdateDeploymentTarget409JSONResponse) VisitUpdateDeploymentTargetResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateDeploymentTargetdefaultJSONResponse struct {
	Body       Error
	StatusCode int
}

func (response UpdateDeploymentTargetdefaultJSONResponse) VisitUpdateDeploymentTargetResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type CreateReleaseRequestObject struct {
	DeploymentTargetId openapi_types.UUID `json:"deploymentTargetId"`
	Params             CreateReleaseParams
	Body               *CreateReleaseJSONRequestBody
}

type CreateReleaseResponseObject interface {
	VisitCreateReleaseResponse(w http.ResponseWriter) error
}

type CreateRelease201JSONResponse ReleaseAcceptance

func (response CreateRelease201JSONResponse) VisitCreateReleaseResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)
	_, err := buf.WriteTo(w)
	return err
}

type CreateRelease400JSONResponse Error

func (response CreateRelease400JSONResponse) VisitCreateReleaseResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type CreateRelease403JSONResponse Error

func (response CreateRelease403JSONResponse) VisitCreateReleaseResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type CreateRelease404JSONResponse Error

func (response CreateRelease404JSONResponse) VisitCreateReleaseResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type CreateRelease409JSONResponse Error

func (response CreateRelease409JSONResponse) VisitCreateReleaseResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)
	_, err := buf.WriteTo(w)
	return err
}

type CreateReleasedefaultJSONResponse struct {
	Body       Error
	StatusCode int
}

func (response CreateReleasedefaultJSONResponse) VisitCreateReleaseResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type GetRuntimeSnapshotRequestObject struct {
	DeploymentTargetId openapi_types.UUID `json:"deploymentTargetId"`
}

type GetRuntimeSnapshotResponseObject interface {
	VisitGetRuntimeSnapshotResponse(w http.ResponseWriter) error
}

type GetRuntimeSnapshot200JSONResponse RuntimeSnapshot

func (response GetRuntimeSnapshot200JSONResponse) VisitGetRuntimeSnapshotResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetRuntimeSnapshot404JSONResponse Error

func (response GetRuntimeSnapshot404JSONResponse) VisitGetRuntimeSnapshotResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type GetRuntimeSnapshotdefaultJSONResponse struct {
	Body       Error
	StatusCode int
}

func (response GetRuntimeSnapshotdefaultJSONResponse) VisitGetRuntimeSnapshotResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type GetOperationRequestObject struct {
	OperationId openapi_types.UUID `json:"operationId"`
}

type GetOperationResponseObject interface {
	VisitGetOperationResponse(w http.ResponseWriter) error
}

type GetOperation200JSONResponse Operation

func (response GetOperation200JSONResponse) VisitGetOperationResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetOperation404JSONResponse Error

func (response GetOperation404JSONResponse) VisitGetOperationResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type GetOperationdefaultJSONResponse struct {
	Body       Error
	StatusCode int
}

func (response GetOperationdefaultJSONResponse) VisitGetOperationResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type CreateProjectRequestObject struct {
	Params CreateProjectParams
	Body   *CreateProjectJSONRequestBody
}

type CreateProjectResponseObject interface {
	VisitCreateProjectResponse(w http.ResponseWriter) error
}

type CreateProject201JSONResponse Project

func (response CreateProject201JSONResponse) VisitCreateProjectResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)
	_, err := buf.WriteTo(w)
	return err
}

type CreateProject409JSONResponse Error

func (response CreateProject409JSONResponse) VisitCreateProjectResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)
	_, err := buf.WriteTo(w)
	return err
}

type CreateProjectdefaultJSONResponse struct {
	Body       Error
	StatusCode int
}

func (response CreateProjectdefaultJSONResponse) VisitCreateProjectResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type GetProjectRequestObject struct {
	ProjectId openapi_types.UUID `json:"projectId"`
}

type GetProjectResponseObject interface {
	VisitGetProjectResponse(w http.ResponseWriter) error
}

type GetProject200JSONResponse Project

func (response GetProject200JSONResponse) VisitGetProjectResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetProject404JSONResponse Error

func (response GetProject404JSONResponse) VisitGetProjectResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type GetProjectdefaultJSONResponse struct {
	Body       Error
	StatusCode int
}

func (response GetProjectdefaultJSONResponse) VisitGetProjectResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type CreateApplicationRequestObject struct {
	ProjectId openapi_types.UUID `json:"projectId"`
	Params    CreateApplicationParams
	Body      *CreateApplicationJSONRequestBody
}

type CreateApplicationResponseObject interface {
	VisitCreateApplicationResponse(w http.ResponseWriter) error
}

type CreateApplication201JSONResponse Application

func (response CreateApplication201JSONResponse) VisitCreateApplicationResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)
	_, err := buf.WriteTo(w)
	return err
}

type CreateApplication403JSONResponse Error

func (response CreateApplication403JSONResponse) VisitCreateApplicationResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type CreateApplication404JSONResponse Error

func (response CreateApplication404JSONResponse) VisitCreateApplicationResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type CreateApplication409JSONResponse Error

func (response CreateApplication409JSONResponse) VisitCreateApplicationResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)
	_, err := buf.WriteTo(w)
	return err
}

type CreateApplicationdefaultJSONResponse struct {
	Body       Error
	StatusCode int
}

func (response CreateApplicationdefaultJSONResponse) VisitCreateApplicationResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type ListProjectMembersRequestObject struct {
	ProjectId openapi_types.UUID `json:"projectId"`
}

type ListProjectMembersResponseObject interface {
	VisitListProjectMembersResponse(w http.ResponseWriter) error
}

type ListProjectMembers200JSONResponse []ProjectMember

func (response ListProjectMembers200JSONResponse) VisitListProjectMembersResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListProjectMembers404JSONResponse Error

func (response ListProjectMembers404JSONResponse) VisitListProjectMembersResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type ListProjectMembersdefaultJSONResponse struct {
	Body       Error
	StatusCode int
}

func (response ListProjectMembersdefaultJSONResponse) VisitListProjectMembersResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type AddProjectMemberRequestObject struct {
	ProjectId openapi_types.UUID `json:"projectId"`
	Params    AddProjectMemberParams
	Body      *AddProjectMemberJSONRequestBody
}

type AddProjectMemberResponseObject interface {
	VisitAddProjectMemberResponse(w http.ResponseWriter) error
}

type AddProjectMember201JSONResponse ProjectMember

func (response AddProjectMember201JSONResponse) VisitAddProjectMemberResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)
	_, err := buf.WriteTo(w)
	return err
}

type AddProjectMember400JSONResponse Error

func (response AddProjectMember400JSONResponse) VisitAddProjectMemberResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type AddProjectMember403JSONResponse Error

func (response AddProjectMember403JSONResponse) VisitAddProjectMemberResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type AddProjectMember404JSONResponse Error

func (response AddProjectMember404JSONResponse) VisitAddProjectMemberResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type AddProjectMember409JSONResponse Error

func (response AddProjectMember409JSONResponse) VisitAddProjectMemberResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)
	_, err := buf.WriteTo(w)
	return err
}

type AddProjectMemberdefaultJSONResponse struct {
	Body       Error
	StatusCode int
}

func (response AddProjectMemberdefaultJSONResponse) VisitAddProjectMemberResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type RemoveProjectMemberRequestObject struct {
	ProjectId openapi_types.UUID `json:"projectId"`
	ActorId   string             `json:"actorId"`
	Params    RemoveProjectMemberParams
}

type RemoveProjectMemberResponseObject interface {
	VisitRemoveProjectMemberResponse(w http.ResponseWriter) error
}

type RemoveProjectMember200JSONResponse ProjectMember

func (response RemoveProjectMember200JSONResponse) VisitRemoveProjectMemberResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type RemoveProjectMember400JSONResponse Error

func (response RemoveProjectMember400JSONResponse) VisitRemoveProjectMemberResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type RemoveProjectMember403JSONResponse Error

func (response RemoveProjectMember403JSONResponse) VisitRemoveProjectMemberResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type RemoveProjectMember404JSONResponse Error

func (response RemoveProjectMember404JSONResponse) VisitRemoveProjectMemberResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type RemoveProjectMember409JSONResponse Error

func (response RemoveProjectMember409JSONResponse) VisitRemoveProjectMemberResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)
	_, err := buf.WriteTo(w)
	return err
}

type RemoveProjectMemberdefaultJSONResponse struct {
	Body       Error
	StatusCode int
}

func (response RemoveProjectMemberdefaultJSONResponse) VisitRemoveProjectMemberResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateProjectMemberRequestObject struct {
	ProjectId openapi_types.UUID `json:"projectId"`
	ActorId   string             `json:"actorId"`
	Params    UpdateProjectMemberParams
	Body      *UpdateProjectMemberJSONRequestBody
}

type UpdateProjectMemberResponseObject interface {
	VisitUpdateProjectMemberResponse(w http.ResponseWriter) error
}

type UpdateProjectMember200JSONResponse ProjectMember

func (response UpdateProjectMember200JSONResponse) VisitUpdateProjectMemberResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateProjectMember400JSONResponse Error

func (response UpdateProjectMember400JSONResponse) VisitUpdateProjectMemberResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateProjectMember403JSONResponse Error

func (response UpdateProjectMember403JSONResponse) VisitUpdateProjectMemberResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateProjectMember404JSONResponse Error

func (response UpdateProjectMember404JSONResponse) VisitUpdateProjectMemberResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateProjectMember409JSONResponse Error

func (response UpdateProjectMember409JSONResponse) VisitUpdateProjectMemberResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateProjectMemberdefaultJSONResponse struct {
	Body       Error
	StatusCode int
}

func (response UpdateProjectMemberdefaultJSONResponse) VisitUpdateProjectMemberResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type GetReleaseRequestObject struct {
	ReleaseId openapi_types.UUID `json:"releaseId"`
}

type GetReleaseResponseObject interface {
	VisitGetReleaseResponse(w http.ResponseWriter) error
}

type GetRelease200JSONResponse Release

func (response GetRelease200JSONResponse) VisitGetReleaseResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetRelease404JSONResponse Error

func (response GetRelease404JSONResponse) VisitGetReleaseResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type GetReleasedefaultJSONResponse struct {
	Body       Error
	StatusCode int
}

func (response GetReleasedefaultJSONResponse) VisitGetReleaseResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// GetApplication 查询应用
	// (GET /api/v1/applications/{applicationId})
	GetApplication(ctx context.Context, request GetApplicationRequestObject) (GetApplicationResponseObject, error)
	// CreateDeploymentTarget 创建部署目标
	// (POST /api/v1/applications/{applicationId}/deployment-targets)
	CreateDeploymentTarget(ctx context.Context, request CreateDeploymentTargetRequestObject) (CreateDeploymentTargetResponseObject, error)
	// GetDeploymentTarget 查询部署目标
	// (GET /api/v1/deployment-targets/{deploymentTargetId})
	GetDeploymentTarget(ctx context.Context, request GetDeploymentTargetRequestObject) (GetDeploymentTargetResponseObject, error)
	// UpdateDeploymentTarget 更新部署目标的可变期望配置
	// (PUT /api/v1/deployment-targets/{deploymentTargetId})
	UpdateDeploymentTarget(ctx context.Context, request UpdateDeploymentTargetRequestObject) (UpdateDeploymentTargetResponseObject, error)
	// CreateRelease 创建发布并接纳异步操作
	// (POST /api/v1/deployment-targets/{deploymentTargetId}/releases)
	CreateRelease(ctx context.Context, request CreateReleaseRequestObject) (CreateReleaseResponseObject, error)
	// GetRuntimeSnapshot 从 Kubernetes 查询部署目标的当前运行状态
	// (GET /api/v1/deployment-targets/{deploymentTargetId}/runtime-snapshot)
	GetRuntimeSnapshot(ctx context.Context, request GetRuntimeSnapshotRequestObject) (GetRuntimeSnapshotResponseObject, error)
	// GetOperation 查询异步操作
	// (GET /api/v1/operations/{operationId})
	GetOperation(ctx context.Context, request GetOperationRequestObject) (GetOperationResponseObject, error)
	// CreateProject 创建项目
	// (POST /api/v1/projects)
	CreateProject(ctx context.Context, request CreateProjectRequestObject) (CreateProjectResponseObject, error)
	// GetProject 查询项目
	// (GET /api/v1/projects/{projectId})
	GetProject(ctx context.Context, request GetProjectRequestObject) (GetProjectResponseObject, error)
	// CreateApplication 创建应用
	// (POST /api/v1/projects/{projectId}/applications)
	CreateApplication(ctx context.Context, request CreateApplicationRequestObject) (CreateApplicationResponseObject, error)
	// ListProjectMembers 查询项目成员
	// (GET /api/v1/projects/{projectId}/members)
	ListProjectMembers(ctx context.Context, request ListProjectMembersRequestObject) (ListProjectMembersResponseObject, error)
	// AddProjectMember 添加项目成员
	// (POST /api/v1/projects/{projectId}/members)
	AddProjectMember(ctx context.Context, request AddProjectMemberRequestObject) (AddProjectMemberResponseObject, error)
	// RemoveProjectMember 移除项目成员
	// (DELETE /api/v1/projects/{projectId}/members/{actorId})
	RemoveProjectMember(ctx context.Context, request RemoveProjectMemberRequestObject) (RemoveProjectMemberResponseObject, error)
	// UpdateProjectMember 修改项目成员角色
	// (PUT /api/v1/projects/{projectId}/members/{actorId})
	UpdateProjectMember(ctx context.Context, request UpdateProjectMemberRequestObject) (UpdateProjectMemberResponseObject, error)
	// GetRelease 查询发布
	// (GET /api/v1/releases/{releaseId})
	GetRelease(ctx context.Context, request GetReleaseRequestObject) (GetReleaseResponseObject, error)
}

type StrictHandlerFunc func(ctx *gin.Context, request any) (any, error)
type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

type StrictGinServerOptions struct {
	// RequestErrorHandlerFunc is called when a request cannot be parsed or
	// decoded. It is invoked for JSON bind failures, form parse/bind errors,
	// multipart reader errors, media type parse errors, missing multipart
	// boundaries, and request body read errors. The default returns 400.
	RequestErrorHandlerFunc func(ctx *gin.Context, err error)
	// HandlerErrorFunc is called when the application handler (or any
	// middleware wrapping it) returns a non-nil error. The default returns 500.
	HandlerErrorFunc func(ctx *gin.Context, err error)
	// ResponseErrorHandlerFunc is called when the response object fails to
	// serialize (Visit*Response returns an error) or when the handler returns
	// an unexpected response type. The default returns 500.
	ResponseErrorHandlerFunc func(ctx *gin.Context, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictGinServerOptions{
		RequestErrorHandlerFunc: func(ctx *gin.Context, err error) {
			ctx.JSON(http.StatusBadRequest, gin.H{"msg": err.Error()})
		},
		HandlerErrorFunc: func(ctx *gin.Context, err error) {
			ctx.JSON(http.StatusInternalServerError, gin.H{"msg": err.Error()})
		},
		ResponseErrorHandlerFunc: func(ctx *gin.Context, err error) {
			ctx.JSON(http.StatusInternalServerError, gin.H{"msg": err.Error()})
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictGinServerOptions) ServerInterface {
	if options.RequestErrorHandlerFunc == nil {
		options.RequestErrorHandlerFunc = func(ctx *gin.Context, err error) {
			ctx.JSON(http.StatusBadRequest, gin.H{"msg": err.Error()})
		}
	}
	if options.HandlerErrorFunc == nil {
		options.HandlerErrorFunc = func(ctx *gin.Context, err error) {
			ctx.JSON(http.StatusInternalServerError, gin.H{"msg": err.Error()})
		}
	}
	if options.ResponseErrorHandlerFunc == nil {
		options.ResponseErrorHandlerFunc = func(ctx *gin.Context, err error) {
			ctx.JSON(http.StatusInternalServerError, gin.H{"msg": err.Error()})
		}
	}
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictGinServerOptions
}

// GetApplication operation middleware
func (sh *strictHandler) GetApplication(ctx *gin.Context, applicationId openapi_types.UUID) {
	var request GetApplicationRequestObject

	request.ApplicationId = applicationId

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetApplication(ctx, request.(GetApplicationRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetApplication")
	}

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(GetApplicationResponseObject); ok {
		if err := validResponse.VisitGetApplicationResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreateDeploymentTarget operation middleware
func (sh *strictHandler) CreateDeploymentTarget(ctx *gin.Context, applicationId openapi_types.UUID, params CreateDeploymentTargetParams) {
	var request CreateDeploymentTargetRequestObject

	request.ApplicationId = applicationId
	request.Params = params

	var body CreateDeploymentTargetJSONRequestBody
	if err := ctx.ShouldBindJSON(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(ctx, err)
		return
	}
	request.Body = &body

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.CreateDeploymentTarget(ctx, request.(CreateDeploymentTargetRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateDeploymentTarget")
	}

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(CreateDeploymentTargetResponseObject); ok {
		if err := validResponse.VisitCreateDeploymentTargetResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetDeploymentTarget operation middleware
func (sh *strictHandler) GetDeploymentTarget(ctx *gin.Context, deploymentTargetId openapi_types.UUID) {
	var request GetDeploymentTargetRequestObject

	request.DeploymentTargetId = deploymentTargetId

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetDeploymentTarget(ctx, request.(GetDeploymentTargetRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetDeploymentTarget")
	}

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(GetDeploymentTargetResponseObject); ok {
		if err := validResponse.VisitGetDeploymentTargetResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}

// UpdateDeploymentTarget operation middleware
func (sh *strictHandler) UpdateDeploymentTarget(ctx *gin.Context, deploymentTargetId openapi_types.UUID, params UpdateDeploymentTargetParams) {
	var request UpdateDeploymentTargetRequestObject

	request.DeploymentTargetId = deploymentTargetId
	request.Params = params

	var body UpdateDeploymentTargetJSONRequestBody
	if err := ctx.ShouldBindJSON(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(ctx, err)
		return
	}
	request.Body = &body

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.UpdateDeploymentTarget(ctx, request.(UpdateDeploymentTargetRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "UpdateDeploymentTarget")
	}

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(UpdateDeploymentTargetResponseObject); ok {
		if err := validResponse.VisitUpdateDeploymentTargetResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreateRelease operation middleware
func (sh *strictHandler) CreateRelease(ctx *gin.Context, deploymentTargetId openapi_types.UUID, params CreateReleaseParams) {
	var request CreateReleaseRequestObject

	request.DeploymentTargetId = deploymentTargetId
	request.Params = params

	var body CreateReleaseJSONRequestBody
	if err := ctx.ShouldBindJSON(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(ctx, err)
		return
	}
	request.Body = &body

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.CreateRelease(ctx, request.(CreateReleaseRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateRelease")
	}

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(CreateReleaseResponseObject); ok {
		if err := validResponse.VisitCreateReleaseResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetRuntimeSnapshot operation middleware
func (sh *strictHandler) GetRuntimeSnapshot(ctx *gin.Context, deploymentTargetId openapi_types.UUID) {
	var request GetRuntimeSnapshotRequestObject

	request.DeploymentTargetId = deploymentTargetId

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetRuntimeSnapshot(ctx, request.(GetRuntimeSnapshotRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetRuntimeSnapshot")
	}

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(GetRuntimeSnapshotResponseObject); ok {
		if err := validResponse.VisitGetRuntimeSnapshotResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetOperation operation middleware
func (sh *strictHandler) GetOperation(ctx *gin.Context, operationId openapi_types.UUID) {
	var request GetOperationRequestObject

	request.OperationId = operationId

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetOperation(ctx, request.(GetOperationRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetOperation")
	}

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(GetOperationResponseObject); ok {
		if err := validResponse.VisitGetOperationResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreateProject operation middleware
func (sh *strictHandler) CreateProject(ctx *gin.Context, params CreateProjectParams) {
	var request CreateProjectRequestObject

	request.Params = params

	var body CreateProjectJSONRequestBody
	if err := ctx.ShouldBindJSON(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(ctx, err)
		return
	}
	request.Body = &body

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.CreateProject(ctx, request.(CreateProjectRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateProject")
	}

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(CreateProjectResponseObject); ok {
		if err := validResponse.VisitCreateProjectResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetProject operation middleware
func (sh *strictHandler) GetProject(ctx *gin.Context, projectId openapi_types.UUID) {
	var request GetProjectRequestObject

	request.ProjectId = projectId

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetProject(ctx, request.(GetProjectRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetProject")
	}

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(GetProjectResponseObject); ok {
		if err := validResponse.VisitGetProjectResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreateApplication operation middleware
func (sh *strictHandler) CreateApplication(ctx *gin.Context, projectId openapi_types.UUID, params CreateApplicationParams) {
	var request CreateApplicationRequestObject

	request.ProjectId = projectId
	request.Params = params

	var body CreateApplicationJSONRequestBody
	if err := ctx.ShouldBindJSON(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(ctx, err)
		return
	}
	request.Body = &body

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.CreateApplication(ctx, request.(CreateApplicationRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateApplication")
	}

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(CreateApplicationResponseObject); ok {
		if err := validResponse.VisitCreateApplicationResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListProjectMembers operation middleware
func (sh *strictHandler) ListProjectMembers(ctx *gin.Context, projectId openapi_types.UUID) {
	var request ListProjectMembersRequestObject

	request.ProjectId = projectId

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.ListProjectMembers(ctx, request.(ListProjectMembersRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListProjectMembers")
	}

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(ListProjectMembersResponseObject); ok {
		if err := validResponse.VisitListProjectMembersResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}

// AddProjectMember operation middleware
func (sh *strictHandler) AddProjectMember(ctx *gin.Context, projectId openapi_types.UUID, params AddProjectMemberParams) {
	var request AddProjectMemberRequestObject

	request.ProjectId = projectId
	request.Params = params

	var body AddProjectMemberJSONRequestBody
	if err := ctx.ShouldBindJSON(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(ctx, err)
		return
	}
	request.Body = &body

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.AddProjectMember(ctx, request.(AddProjectMemberRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "AddProjectMember")
	}

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(AddProjectMemberResponseObject); ok {
		if err := validResponse.VisitAddProjectMemberResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}

// RemoveProjectMember operation middleware
func (sh *strictHandler) RemoveProjectMember(ctx *gin.Context, projectId openapi_types.UUID, actorId string, params RemoveProjectMemberParams) {
	var request RemoveProjectMemberRequestObject

	request.ProjectId = projectId
	request.ActorId = actorId
	request.Params = params

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.RemoveProjectMember(ctx, request.(RemoveProjectMemberRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "RemoveProjectMember")
	}

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(RemoveProjectMemberResponseObject); ok {
		if err := validResponse.VisitRemoveProjectMemberResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}

// UpdateProjectMember operation middleware
func (sh *strictHandler) UpdateProjectMember(ctx *gin.Context, projectId openapi_types.UUID, actorId string, params UpdateProjectMemberParams) {
	var request UpdateProjectMemberRequestObject

	request.ProjectId = projectId
	request.ActorId = actorId
	request.Params = params

	var body UpdateProjectMemberJSONRequestBody
	if err := ctx.ShouldBindJSON(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(ctx, err)
		return
	}
	request.Body = &body

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.UpdateProjectMember(ctx, request.(UpdateProjectMemberRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "UpdateProjectMember")
	}

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(UpdateProjectMemberResponseObject); ok {
		if err := validResponse.VisitUpdateProjectMemberResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetRelease operation middleware
func (sh *strictHandler) GetRelease(ctx *gin.Context, releaseId openapi_types.UUID) {
	var request GetReleaseRequestObject

	request.ReleaseId = releaseId

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetRelease(ctx, request.(GetReleaseRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetRelease")
	}

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(GetReleaseResponseObject); ok {
		if err := validResponse.VisitGetReleaseResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"7FxbcxNHFv4rqtk87cpIxsAGPcWB1K4r2cXlsE8up2qsObIn0Vwy3TJhVapyMHZMCl/YcHGwt4AUBCpZ",
	"7I1DYWOb5cesZkZ+yl9IdfdI6tH0jDTCSJPgFwpL093n+p1z+pxRWcobmmnooGMk5cqSKVuyBhgs+teI",
	"ApppYNDzlz+Ey+QTBVDeUk2sGrqUk+yX39jXlpxvlqovN2qz89XdZXvhW+/P63P2+jN7Yd69e9V+ccV9",
	"es25/1Vta+H/s1ektKSS1dMgK2BJaUmXNZBy/GkD5Li0ZMHnJdUCRcphqwRpCeWnQZMJHZr8xUegT+Fp",
	"KTd48t20pKl6/e930xK+bJINEbZUfUqqVCr1pZSrYUUZtYxPIY//BtokWGPweQkQJl/JiqIS3uTiqGWY",
	"YGEVkJQryEUEacnkPipLch4b1ojShpjBADFpyTKKQJa9Y0FBykl/yDRVkPHIzHgEjpFHCflNSYw3TvZ2",
	"mmgcYUySNeSIYdMsqnmZqSkWW3kLZAzKMBVHwbA0GUs5SZExDGBVA0nAj7fkfWoggW9VxbdTqaQqok2Y",
	"DQjWm0wSI51tg4qlKcE2LRKka5sbe6d7q3mG0pw8RHI+R7/lpN2dLdWZ5w0pm21rSHVmuWVnhlpXmTLG",
	"YBF/+2RcHvjnBPknO3B2YOKP7wQF2CInXizh7J8Hs2hc1kDHF2VrCnB3MsgbOpZVHaxRw8IeV6pW0qTc",
	"mdOnh05TttjfTVGoOoYpsKhTAdUB8q1suwpheYpKHnTyzLikwAwUDZMww3EcIh62mjs73cJFuMzq/v0W",
	"mssYFEFG0B3rqiZPwRgUwAI9D4KIdH3eXv0xhablk6fPpM6rU4Bwyr17tbq7ZK9s2StrqQvnRlKHtzbs",
	"uRX74JZ78wkLSJxMTg+e9Anlz0N+qXwynkOmnIfcxHsTf3qPnZQblwcK2YGzE+UzpyrtBdXChUhWrU4V",
	"Nzo1IalD5MwXSwiTYFgQwnDAPYPO1M/QQTUi3IQHhtcGgLRUMpV4TIpCj1876QaQcDrg2YpAmLBgxRMq",
	"Mq8PLMuwYiO0IhaxBgh5Yoxmnu7QfF5E2AUTrG7yFuKgmonPGSWdRY867mdFuO89zSAFg4ba5WMNsobZ",
	"SrKJt61sWfLlN2L/QJR0TsYwZVgRT3xc0jQ55IGCqqtoOh5RHbqdGigOBL5Hob7T3A3LVkz5ISzjEuL9",
	"1wRdIV+mJauk6+x/qJTPAyhATi3IahEUoWuzD5pbedSfUCgUvzk0oI/wwvI7dYucG0yn/TYf5v2csUf6",
	"W92w47ldsk1UL5H6zgcHYWng61tebHu7ZFifgVdCdmAmHjPcOs4UmhyIlOxlm7/1UjBGcddtQee7GOj+",
	"RiBMMEcny3hlcewrh9eHNr68brmx6DZp4SnkHM+4pFO/8FI3+v8ZFS6BJXQ7r/7otzMoLQn+SKdRt7PH",
	"AnVSMNzRYz/WZRNNG7iddXhSu+hfJPQ9AWcBggLHx3FSj5bhfB5MLHv8xdClweeYHWV9XDLToaACoqkv",
	"T3PHRzB3MaCdhFd/0VVYTLg6ypotCpeOrA4TarKkE2g4Z+hMcTGVGF5VETpkxDaMSExCE9xoAXnpaCO1",
	"8M6KLts8XkcNpcu7rKDFTHvOJmJe4TF10jCKIOuRchHfVLEz6js2lkcw2K1DzshqUZ4swhh/TRlZoubr",
	"ZtN5kRowOEGR2gTnD75QEUZiOTaf+nuYfrqMXwogooTO5dC+wihYgKZ1QL5snH5IMgq9IXthNmBMIrBm",
	"4gV201BiK4V4hkAd1PI6F0bMgtooWXkfUn5WmgRLBwwoqpztlJ4WpxLGfY8Gn6B5lQVsTWCiQasJktoq",
	"yrTA53xO5alR5Ov/oHsftzXiBDsmsyPoq75udzSkJ0oeU/WCEWwZXLAmVXzBRCl776Z780l172F1f81Z",
	"fmwvPrdf/Hz47+/cu1ft+f/YB7Opv168OJqyH91w975nbQOsYkJtc4/h0RFSfYCF2ObZE4MnshRnTNBl",
	"U5Vy0tCJ7IkhifYUpinHGdlUMzODGS4bQZmyLzepkOe8LkAjfSQoIP0FMN/sTfs6+ONl1mknRzX77K1Z",
	"T3iXvQ3CVCbIYmQaOmK6O5nN1m0e2DUsd1bmUy80N/eP0jHPFdVeS6OHKqu29b0zN0/keyp76siOZpfj",
	"oYdWd5fsp2v2xhMWzwpyqYjf/Nm1rR3npyv2w59qzx5Ro0f1OzXJufeotvUdI45+1YlFZZowO8BqMTYA",
	"YiCBlYkbvT22trRYck0SMi3zKsw+KQi9b7CU8Uh0FN32rvgRiXBZCfjJ4JERE1CKwHYO5564L7fd9U3n",
	"/lf2zra9uG7v7zGvGeqB19ApocMHL9z1zdrjf9WubVd3l2pzLxkZPG39dORT2bM9OJdOQh3e3LR3tt39",
	"FRpulgkZq9eZfycFUkS64YAliB2ZcjD9i4xaXYGJMMVMZvyK65c9DmX80QkNaK3IYJYEliTO1fthTIkJ",
	"T9HlS0fhKdvP8OSsP3Nu/7fv4an6atO5+aIv4SnUOY+DlA8mqKHwwiKlGh3zcjbuORvrh/NL7svNbiJX",
	"xrtpaZsTjzWu9d9ewBHO9fU4DQ72hESWvXLD3p2r7i7b/5u3H151VxfYsDrJiZfv2U9X+cw42wM/5+YQ",
	"q7tLztqWs3HNubUYGFhkjyQkY2dSPAbDJGbsTDf2i+fO8iN372f74Irz9BEz8u5gkN1eDyCu7xGW0be2",
	"SH5nCX0rewL1fNi4Xk/VXq3WHlx37jy3X/3ozj/+5WCdeXRt89XhnU3nzvNU4w48Vd3dS/F9iuMaQMpJ",
	"1f3lFCfPYElAYj3FKSZq9+vnzuyXPiNvWCjKlDlrjSxLmy3/TsyXX55Uu+WGGIIK8F7W6m3tyQ5N6jVq",
	"GGR6gwNtM8L6sF3AfpKUrLW8f9LjZK0uIhEm0aSj5ZLyOM4HbuaomIT2mSk3RlwikS7UTgU4xw/NJBPl",
	"2ppUr+/X6KFJvVnrzHp8/aN2sBe3C3k0JpWwGljwJmiPobWjtmnSekD11mX/fPM4xghqyWBDWYgSGp32",
	"QKGx5iMVYd9gCPoNxZyOZrz8bw0ExrzCLNBZXLVvrNmLd2oP+mb8zuLtwK84LDlrWzyFSQxeTcrEQan1",
	"Rx7expgU9kMX/cn2697Rxht2tp2dffvr+z27hB3OY8NKjZxPOYu3+QDl3Lnv3Frse4R0Nx+4qwtNc08y",
	"SPQkijbsxN1faZLXCK0L2+4PXyYGsagp+8XUYTjNlL23pipsZLEIGIIwNwaaMQN9RDrRxFfzba9ufr9n",
	"8MgQ9c2WmuF4Rmzz8f7htw/du1eDLtJTSHvrMcxZvM3ObYDZLwfXncXbtdn5BEEauxA9uMvMxtmYtVeX",
	"q7uz1d0fUvTtRkZzQkGOER1Iy8KndY7hqqeTQN3ngNn+5IAMOuydbTaCc5wJHqPo7x9FvXGzgBv4Esb6",
	"VFKm3HgTLPKOP850Ev/7IwntwDderQ6Z7On16yDeOFEy+5jelE6lUvk1AAD//w==",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
