// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/flate"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/gin-gonic/gin"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for CreateDeploymentTargetRequestStage.
const (
	CreateDeploymentTargetRequestStageDevelopment CreateDeploymentTargetRequestStage = "development"
)

// Valid indicates whether the value is a known member of the CreateDeploymentTargetRequestStage enum.
func (e CreateDeploymentTargetRequestStage) Valid() bool {
	switch e {
	case CreateDeploymentTargetRequestStageDevelopment:
		return true
	default:
		return false
	}
}

// Defines values for DeploymentTargetStage.
const (
	DeploymentTargetStageDevelopment DeploymentTargetStage = "development"
)

// Valid indicates whether the value is a known member of the DeploymentTargetStage enum.
func (e DeploymentTargetStage) Valid() bool {
	switch e {
	case DeploymentTargetStageDevelopment:
		return true
	default:
		return false
	}
}

// Defines values for OperationStatus.
const (
	OperationStatusFailed    OperationStatus = "failed"
	OperationStatusPending   OperationStatus = "pending"
	OperationStatusRunning   OperationStatus = "running"
	OperationStatusSucceeded OperationStatus = "succeeded"
)

// Valid indicates whether the value is a known member of the OperationStatus enum.
func (e OperationStatus) Valid() bool {
	switch e {
	case OperationStatusFailed:
		return true
	case OperationStatusPending:
		return true
	case OperationStatusRunning:
		return true
	case OperationStatusSucceeded:
		return true
	default:
		return false
	}
}

// Defines values for OperationType.
const (
	ReleaseDeploy OperationType = "release.deploy"
)

// Valid indicates whether the value is a known member of the OperationType enum.
func (e OperationType) Valid() bool {
	switch e {
	case ReleaseDeploy:
		return true
	default:
		return false
	}
}

// Defines values for OperationAttemptStatus.
const (
	OperationAttemptStatusFailed    OperationAttemptStatus = "failed"
	OperationAttemptStatusRunning   OperationAttemptStatus = "running"
	OperationAttemptStatusSucceeded OperationAttemptStatus = "succeeded"
)

// Valid indicates whether the value is a known member of the OperationAttemptStatus enum.
func (e OperationAttemptStatus) Valid() bool {
	switch e {
	case OperationAttemptStatusFailed:
		return true
	case OperationAttemptStatusRunning:
		return true
	case OperationAttemptStatusSucceeded:
		return true
	default:
		return false
	}
}

// Defines values for ReleaseTargetSnapshotStage.
const (
	ReleaseTargetSnapshotStageDevelopment ReleaseTargetSnapshotStage = "development"
)

// Valid indicates whether the value is a known member of the ReleaseTargetSnapshotStage enum.
func (e ReleaseTargetSnapshotStage) Valid() bool {
	switch e {
	case ReleaseTargetSnapshotStageDevelopment:
		return true
	default:
		return false
	}
}

// Defines values for RuntimeSnapshotFreshness.
const (
	Fresh       RuntimeSnapshotFreshness = "fresh"
	Unavailable RuntimeSnapshotFreshness = "unavailable"
)

// Valid indicates whether the value is a known member of the RuntimeSnapshotFreshness enum.
func (e RuntimeSnapshotFreshness) Valid() bool {
	switch e {
	case Fresh:
		return true
	case Unavailable:
		return true
	default:
		return false
	}
}

// Defines values for RuntimeSnapshotSource.
const (
	Kubernetes RuntimeSnapshotSource = "kubernetes"
)

// Valid indicates whether the value is a known member of the RuntimeSnapshotSource enum.
func (e RuntimeSnapshotSource) Valid() bool {
	switch e {
	case Kubernetes:
		return true
	default:
		return false
	}
}

// Defines values for UpdateDeploymentTargetRequestStage.
const (
	UpdateDeploymentTargetRequestStageDevelopment UpdateDeploymentTargetRequestStage = "development"
)

// Valid indicates whether the value is a known member of the UpdateDeploymentTargetRequestStage enum.
func (e UpdateDeploymentTargetRequestStage) Valid() bool {
	switch e {
	case UpdateDeploymentTargetRequestStageDevelopment:
		return true
	default:
		return false
	}
}

// Application defines model for Application.
type Application struct {
	CreatedAt time.Time          `json:"createdAt"`
	CreatedBy string             `json:"createdBy"`
	Id        openapi_types.UUID `json:"id"`
	Name      string             `json:"name"`
	ProjectId openapi_types.UUID `json:"projectId"`
	Slug      string             `json:"slug"`
}

// CreateApplicationRequest defines model for CreateApplicationRequest.
type CreateApplicationRequest struct {
	Name string `json:"name"`
	Slug string `json:"slug"`
}

// CreateDeploymentTargetRequest defines model for CreateDeploymentTargetRequest.
type CreateDeploymentTargetRequest struct {
	ContainerPort int                                `json:"containerPort"`
	Replicas      int                                `json:"replicas"`
	Stage         CreateDeploymentTargetRequestStage `json:"stage"`
}

// CreateDeploymentTargetRequestStage defines model for CreateDeploymentTargetRequest.Stage.
type CreateDeploymentTargetRequestStage string

// CreateProjectRequest defines model for CreateProjectRequest.
type CreateProjectRequest struct {
	Name string `json:"name"`
	Slug string `json:"slug"`
}

// CreateReleaseRequest defines model for CreateReleaseRequest.
type CreateReleaseRequest struct {
	// ImageReference 包含 sha256 Digest 的不可变 OCI 镜像引用。
	ImageReference string `json:"imageReference"`
}

// DeploymentTarget defines model for DeploymentTarget.
type DeploymentTarget struct {
	ApplicationId openapi_types.UUID    `json:"applicationId"`
	ClusterRef    string                `json:"clusterRef"`
	ContainerPort int                   `json:"containerPort"`
	CreatedAt     time.Time             `json:"createdAt"`
	CreatedBy     string                `json:"createdBy"`
	Id            openapi_types.UUID    `json:"id"`
	Namespace     string                `json:"namespace"`
	Replicas      int                   `json:"replicas"`
	Stage         DeploymentTargetStage `json:"stage"`
	UpdatedAt     time.Time             `json:"updatedAt"`
}

// DeploymentTargetStage defines model for DeploymentTarget.Stage.
type DeploymentTargetStage string

// Error defines model for Error.
type Error struct {
	Code    string `json:"code"`
	Message string `json:"message"`
}

// Operation defines model for Operation.
type Operation struct {
	AttemptCount   int                `json:"attemptCount"`
	Attempts       []OperationAttempt `json:"attempts"`
	CreatedAt      time.Time          `json:"createdAt"`
	CreatedBy      string             `json:"createdBy"`
	ErrorCategory  *string            `json:"errorCategory,omitempty"`
	ErrorSummary   *string            `json:"errorSummary,omitempty"`
	FinishedAt     *time.Time         `json:"finishedAt,omitempty"`
	Id             openapi_types.UUID `json:"id"`
	IdempotencyKey string             `json:"idempotencyKey"`
	ReleaseId      openapi_types.UUID `json:"releaseId"`
	StartedAt      *time.Time         `json:"startedAt,omitempty"`
	Status         OperationStatus    `json:"status"`
	Type           OperationType      `json:"type"`
	UpdatedAt      time.Time          `json:"updatedAt"`
}

// OperationStatus defines model for Operation.Status.
type OperationStatus string

// OperationType defines model for Operation.Type.
type OperationType string

// OperationAttempt defines model for OperationAttempt.
type OperationAttempt struct {
	ErrorCategory *string                `json:"errorCategory,omitempty"`
	ErrorSummary  *string                `json:"errorSummary,omitempty"`
	FinishedAt    *time.Time             `json:"finishedAt,omitempty"`
	Id            openapi_types.UUID     `json:"id"`
	Number        int                    `json:"number"`
	StartedAt     time.Time              `json:"startedAt"`
	Status        OperationAttemptStatus `json:"status"`
	WorkerId      string                 `json:"workerId"`
}

// OperationAttemptStatus defines model for OperationAttempt.Status.
type OperationAttemptStatus string

// Project defines model for Project.
type Project struct {
	CreatedAt time.Time          `json:"createdAt"`
	CreatedBy string             `json:"createdBy"`
	Id        openapi_types.UUID `json:"id"`
	Name      string             `json:"name"`
	Slug      string             `json:"slug"`
}

// Release defines model for Release.
type Release struct {
	CreatedAt          time.Time             `json:"createdAt"`
	CreatedBy          string                `json:"createdBy"`
	DeploymentTargetId openapi_types.UUID    `json:"deploymentTargetId"`
	Id                 openapi_types.UUID    `json:"id"`
	ImageReference     string                `json:"imageReference"`
	TargetSnapshot     ReleaseTargetSnapshot `json:"targetSnapshot"`
}

// ReleaseAcceptance defines model for ReleaseAcceptance.
type ReleaseAcceptance struct {
	Operation Operation `json:"operation"`
	Release   Release   `json:"release"`
}

// ReleaseTargetSnapshot defines model for ReleaseTargetSnapshot.
type ReleaseTargetSnapshot struct {
	ApplicationId openapi_types.UUID         `json:"applicationId"`
	ClusterRef    string                     `json:"clusterRef"`
	ContainerPort int                        `json:"containerPort"`
	Namespace     string                     `json:"namespace"`
	ProjectId     openapi_types.UUID         `json:"projectId"`
	Replicas      int                        `json:"replicas"`
	Stage         ReleaseTargetSnapshotStage `json:"stage"`
}

// ReleaseTargetSnapshotStage defines model for ReleaseTargetSnapshot.Stage.
type ReleaseTargetSnapshotStage string

// RuntimeCondition defines model for RuntimeCondition.
type RuntimeCondition struct {
	Message string `json:"message"`
	Reason  string `json:"reason"`
	Status  string `json:"status"`
	Type    string `json:"type"`
}

// RuntimePod defines model for RuntimePod.
type RuntimePod struct {
	Name   string `json:"name"`
	Phase  string `json:"phase"`
	Ready  bool   `json:"ready"`
	Reason string `json:"reason"`
}

// RuntimeSnapshot defines model for RuntimeSnapshot.
type RuntimeSnapshot struct {
	AvailableReplicas  int                      `json:"availableReplicas"`
	Conditions         []RuntimeCondition       `json:"conditions"`
	DeploymentExists   bool                     `json:"deploymentExists"`
	DeploymentName     string                   `json:"deploymentName"`
	DeploymentTargetId openapi_types.UUID       `json:"deploymentTargetId"`
	DesiredReplicas    int                      `json:"desiredReplicas"`
	ErrorCategory      *string                  `json:"errorCategory,omitempty"`
	Freshness          RuntimeSnapshotFreshness `json:"freshness"`
	ObservedAt         time.Time                `json:"observedAt"`
	Pods               []RuntimePod             `json:"pods"`
	ReadyReplicas      int                      `json:"readyReplicas"`
	ReleaseId          *openapi_types.UUID      `json:"releaseId,omitempty"`
	Source             RuntimeSnapshotSource    `json:"source"`
	UpdatedReplicas    int                      `json:"updatedReplicas"`
}

// RuntimeSnapshotFreshness defines model for RuntimeSnapshot.Freshness.
type RuntimeSnapshotFreshness string

// RuntimeSnapshotSource defines model for RuntimeSnapshot.Source.
type RuntimeSnapshotSource string

// UpdateDeploymentTargetRequest defines model for UpdateDeploymentTargetRequest.
type UpdateDeploymentTargetRequest struct {
	ContainerPort int                                `json:"containerPort"`
	Replicas      int                                `json:"replicas"`
	Stage         UpdateDeploymentTargetRequestStage `json:"stage"`
}

// UpdateDeploymentTargetRequestStage defines model for UpdateDeploymentTargetRequest.Stage.
type UpdateDeploymentTargetRequestStage string

// IdempotencyKey defines model for IdempotencyKey.
type IdempotencyKey = string

// CreateDeploymentTargetParams defines parameters for CreateDeploymentTarget.
type CreateDeploymentTargetParams struct {
	// IdempotencyKey 当前操作者与写操作范围内的幂等标识。
	IdempotencyKey IdempotencyKey `json:"Idempotency-Key"`
}

// UpdateDeploymentTargetParams defines parameters for UpdateDeploymentTarget.
type UpdateDeploymentTargetParams struct {
	// IdempotencyKey 当前操作者与写操作范围内的幂等标识。
	IdempotencyKey IdempotencyKey `json:"Idempotency-Key"`
}

// CreateReleaseParams defines parameters for CreateRelease.
type CreateReleaseParams struct {
	// IdempotencyKey 当前操作者与写操作范围内的幂等标识。
	IdempotencyKey IdempotencyKey `json:"Idempotency-Key"`
}

// CreateProjectParams defines parameters for CreateProject.
type CreateProjectParams struct {
	// IdempotencyKey 当前操作者与写操作范围内的幂等标识。
	IdempotencyKey IdempotencyKey `json:"Idempotency-Key"`
}

// CreateApplicationParams defines parameters for CreateApplication.
type CreateApplicationParams struct {
	// IdempotencyKey 当前操作者与写操作范围内的幂等标识。
	IdempotencyKey IdempotencyKey `json:"Idempotency-Key"`
}

// CreateDeploymentTargetJSONRequestBody defines body for CreateDeploymentTarget for application/json ContentType.
type CreateDeploymentTargetJSONRequestBody = CreateDeploymentTargetRequest

// UpdateDeploymentTargetJSONRequestBody defines body for UpdateDeploymentTarget for application/json ContentType.
type UpdateDeploymentTargetJSONRequestBody = UpdateDeploymentTargetRequest

// CreateReleaseJSONRequestBody defines body for CreateRelease for application/json ContentType.
type CreateReleaseJSONRequestBody = CreateReleaseRequest

// CreateProjectJSONRequestBody defines body for CreateProject for application/json ContentType.
type CreateProjectJSONRequestBody = CreateProjectRequest

// CreateApplicationJSONRequestBody defines body for CreateApplication for application/json ContentType.
type CreateApplicationJSONRequestBody = CreateApplicationRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// GetApplication 查询应用
	// (GET /api/v1/applications/{applicationId})
	GetApplication(c *gin.Context, applicationId openapi_types.UUID)
	// CreateDeploymentTarget 创建部署目标
	// (POST /api/v1/applications/{applicationId}/deployment-targets)
	CreateDeploymentTarget(c *gin.Context, applicationId openapi_types.UUID, params CreateDeploymentTargetParams)
	// GetDeploymentTarget 查询部署目标
	// (GET /api/v1/deployment-targets/{deploymentTargetId})
	GetDeploymentTarget(c *gin.Context, deploymentTargetId openapi_types.UUID)
	// UpdateDeploymentTarget 更新部署目标的可变期望配置
	// (PUT /api/v1/deployment-targets/{deploymentTargetId})
	UpdateDeploymentTarget(c *gin.Context, deploymentTargetId openapi_types.UUID, params UpdateDeploymentTargetParams)
	// CreateRelease 创建发布并接纳异步操作
	// (POST /api/v1/deployment-targets/{deploymentTargetId}/releases)
	CreateRelease(c *gin.Context, deploymentTargetId openapi_types.UUID, params CreateReleaseParams)
	// GetRuntimeSnapshot 从 Kubernetes 查询部署目标的当前运行状态
	// (GET /api/v1/deployment-targets/{deploymentTargetId}/runtime-snapshot)
	GetRuntimeSnapshot(c *gin.Context, deploymentTargetId openapi_types.UUID)
	// GetOperation 查询异步操作
	// (GET /api/v1/operations/{operationId})
	GetOperation(c *gin.Context, operationId openapi_types.UUID)
	// CreateProject 创建项目
	// (POST /api/v1/projects)
	CreateProject(c *gin.Context, params CreateProjectParams)
	// GetProject 查询项目
	// (GET /api/v1/projects/{projectId})
	GetProject(c *gin.Context, projectId openapi_types.UUID)
	// CreateApplication 创建应用
	// (POST /api/v1/projects/{projectId}/applications)
	CreateApplication(c *gin.Context, projectId openapi_types.UUID, params CreateApplicationParams)
	// GetRelease 查询发布
	// (GET /api/v1/releases/{releaseId})
	GetRelease(c *gin.Context, releaseId openapi_types.UUID)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// GetApplication operation middleware
func (siw *ServerInterfaceWrapper) GetApplication(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "applicationId" -------------
	var applicationId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "applicationId", c.Param("applicationId"), &applicationId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter applicationId: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetApplication(c, applicationId)
}

// CreateDeploymentTarget operation middleware
func (siw *ServerInterfaceWrapper) CreateDeploymentTarget(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "applicationId" -------------
	var applicationId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "applicationId", c.Param("applicationId"), &applicationId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter applicationId: %w", err), http.StatusBadRequest)
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params CreateDeploymentTargetParams

	headers := c.Request.Header

	// ------------- Required header parameter "Idempotency-Key" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Idempotency-Key")]; found {
		var IdempotencyKey IdempotencyKey
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandler(c, fmt.Errorf("Expected one value for Idempotency-Key, got %d", n), http.StatusBadRequest)
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Idempotency-Key", valueList[0], &IdempotencyKey, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter Idempotency-Key: %w", err), http.StatusBadRequest)
			return
		}

		params.IdempotencyKey = IdempotencyKey

	} else {
		siw.ErrorHandler(c, fmt.Errorf("Header parameter Idempotency-Key is required, but not found"), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.CreateDeploymentTarget(c, applicationId, params)
}

// GetDeploymentTarget operation middleware
func (siw *ServerInterfaceWrapper) GetDeploymentTarget(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "deploymentTargetId" -------------
	var deploymentTargetId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "deploymentTargetId", c.Param("deploymentTargetId"), &deploymentTargetId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter deploymentTargetId: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetDeploymentTarget(c, deploymentTargetId)
}

// UpdateDeploymentTarget operation middleware
func (siw *ServerInterfaceWrapper) UpdateDeploymentTarget(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "deploymentTargetId" -------------
	var deploymentTargetId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "deploymentTargetId", c.Param("deploymentTargetId"), &deploymentTargetId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter deploymentTargetId: %w", err), http.StatusBadRequest)
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params UpdateDeploymentTargetParams

	headers := c.Request.Header

	// ------------- Required header parameter "Idempotency-Key" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Idempotency-Key")]; found {
		var IdempotencyKey IdempotencyKey
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandler(c, fmt.Errorf("Expected one value for Idempotency-Key, got %d", n), http.StatusBadRequest)
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Idempotency-Key", valueList[0], &IdempotencyKey, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter Idempotency-Key: %w", err), http.StatusBadRequest)
			return
		}

		params.IdempotencyKey = IdempotencyKey

	} else {
		siw.ErrorHandler(c, fmt.Errorf("Header parameter Idempotency-Key is required, but not found"), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.UpdateDeploymentTarget(c, deploymentTargetId, params)
}

// CreateRelease operation middleware
func (siw *ServerInterfaceWrapper) CreateRelease(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "deploymentTargetId" -------------
	var deploymentTargetId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "deploymentTargetId", c.Param("deploymentTargetId"), &deploymentTargetId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter deploymentTargetId: %w", err), http.StatusBadRequest)
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params CreateReleaseParams

	headers := c.Request.Header

	// ------------- Required header parameter "Idempotency-Key" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Idempotency-Key")]; found {
		var IdempotencyKey IdempotencyKey
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandler(c, fmt.Errorf("Expected one value for Idempotency-Key, got %d", n), http.StatusBadRequest)
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Idempotency-Key", valueList[0], &IdempotencyKey, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter Idempotency-Key: %w", err), http.StatusBadRequest)
			return
		}

		params.IdempotencyKey = IdempotencyKey

	} else {
		siw.ErrorHandler(c, fmt.Errorf("Header parameter Idempotency-Key is required, but not found"), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.CreateRelease(c, deploymentTargetId, params)
}

// GetRuntimeSnapshot operation middleware
func (siw *ServerInterfaceWrapper) GetRuntimeSnapshot(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "deploymentTargetId" -------------
	var deploymentTargetId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "deploymentTargetId", c.Param("deploymentTargetId"), &deploymentTargetId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter deploymentTargetId: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetRuntimeSnapshot(c, deploymentTargetId)
}

// GetOperation operation middleware
func (siw *ServerInterfaceWrapper) GetOperation(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "operationId" -------------
	var operationId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "operationId", c.Param("operationId"), &operationId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter operationId: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetOperation(c, operationId)
}

// CreateProject operation middleware
func (siw *ServerInterfaceWrapper) CreateProject(c *gin.Context) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params CreateProjectParams

	headers := c.Request.Header

	// ------------- Required header parameter "Idempotency-Key" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Idempotency-Key")]; found {
		var IdempotencyKey IdempotencyKey
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandler(c, fmt.Errorf("Expected one value for Idempotency-Key, got %d", n), http.StatusBadRequest)
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Idempotency-Key", valueList[0], &IdempotencyKey, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter Idempotency-Key: %w", err), http.StatusBadRequest)
			return
		}

		params.IdempotencyKey = IdempotencyKey

	} else {
		siw.ErrorHandler(c, fmt.Errorf("Header parameter Idempotency-Key is required, but not found"), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.CreateProject(c, params)
}

// GetProject operation middleware
func (siw *ServerInterfaceWrapper) GetProject(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "projectId" -------------
	var projectId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "projectId", c.Param("projectId"), &projectId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter projectId: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetProject(c, projectId)
}

// CreateApplication operation middleware
func (siw *ServerInterfaceWrapper) CreateApplication(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "projectId" -------------
	var projectId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "projectId", c.Param("projectId"), &projectId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter projectId: %w", err), http.StatusBadRequest)
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params CreateApplicationParams

	headers := c.Request.Header

	// ------------- Required header parameter "Idempotency-Key" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Idempotency-Key")]; found {
		var IdempotencyKey IdempotencyKey
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandler(c, fmt.Errorf("Expected one value for Idempotency-Key, got %d", n), http.StatusBadRequest)
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Idempotency-Key", valueList[0], &IdempotencyKey, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter Idempotency-Key: %w", err), http.StatusBadRequest)
			return
		}

		params.IdempotencyKey = IdempotencyKey

	} else {
		siw.ErrorHandler(c, fmt.Errorf("Header parameter Idempotency-Key is required, but not found"), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.CreateApplication(c, projectId, params)
}

// GetRelease operation middleware
func (siw *ServerInterfaceWrapper) GetRelease(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "releaseId" -------------
	var releaseId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "releaseId", c.Param("releaseId"), &releaseId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter releaseId: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetRelease(c, releaseId)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.POST(options.BaseURL+"/api/v1/projects", wrapper.CreateProject)
	router.GET(options.BaseURL+"/api/v1/projects/:projectId", wrapper.GetProject)
	router.POST(options.BaseURL+"/api/v1/projects/:projectId/applications", wrapper.CreateApplication)
	router.GET(options.BaseURL+"/api/v1/applications/:applicationId", wrapper.GetApplication)
	router.POST(options.BaseURL+"/api/v1/applications/:applicationId/deployment-targets", wrapper.CreateDeploymentTarget)
	router.GET(options.BaseURL+"/api/v1/deployment-targets/:deploymentTargetId", wrapper.GetDeploymentTarget)
	router.PUT(options.BaseURL+"/api/v1/deployment-targets/:deploymentTargetId", wrapper.UpdateDeploymentTarget)
	router.POST(options.BaseURL+"/api/v1/deployment-targets/:deploymentTargetId/releases", wrapper.CreateRelease)
	router.GET(options.BaseURL+"/api/v1/deployment-targets/:deploymentTargetId/runtime-snapshot", wrapper.GetRuntimeSnapshot)
	router.GET(options.BaseURL+"/api/v1/releases/:releaseId", wrapper.GetRelease)
	router.GET(options.BaseURL+"/api/v1/operations/:operationId", wrapper.GetOperation)
}

type GetApplicationRequestObject struct {
	ApplicationId openapi_types.UUID `json:"applicationId"`
}

type GetApplicationResponseObject interface {
	VisitGetApplicationResponse(w http.ResponseWriter) error
}

type GetApplication200JSONResponse Application

func (response GetApplication200JSONResponse) VisitGetApplicationResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetApplication404JSONResponse Error

func (response GetApplication404JSONResponse) VisitGetApplicationResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type GetApplicationdefaultJSONResponse struct {
	Body       Error
	StatusCode int
}

func (response GetApplicationdefaultJSONResponse) VisitGetApplicationResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type CreateDeploymentTargetRequestObject struct {
	ApplicationId openapi_types.UUID `json:"applicationId"`
	Params        CreateDeploymentTargetParams
	Body          *CreateDeploymentTargetJSONRequestBody
}

type CreateDeploymentTargetResponseObject interface {
	VisitCreateDeploymentTargetResponse(w http.ResponseWriter) error
}

type CreateDeploymentTarget201JSONResponse DeploymentTarget

func (response CreateDeploymentTarget201JSONResponse) VisitCreateDeploymentTargetResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)
	_, err := buf.WriteTo(w)
	return err
}

type CreateDeploymentTarget404JSONResponse Error

func (response CreateDeploymentTarget404JSONResponse) VisitCreateDeploymentTargetResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type CreateDeploymentTarget409JSONResponse Error

func (response CreateDeploymentTarget409JSONResponse) VisitCreateDeploymentTargetResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)
	_, err := buf.WriteTo(w)
	return err
}

type CreateDeploymentTargetdefaultJSONResponse struct {
	Body       Error
	StatusCode int
}

func (response CreateDeploymentTargetdefaultJSONResponse) VisitCreateDeploymentTargetResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type GetDeploymentTargetRequestObject struct {
	DeploymentTargetId openapi_types.UUID `json:"deploymentTargetId"`
}

type GetDeploymentTargetResponseObject interface {
	VisitGetDeploymentTargetResponse(w http.ResponseWriter) error
}

type GetDeploymentTarget200JSONResponse DeploymentTarget

func (response GetDeploymentTarget200JSONResponse) VisitGetDeploymentTargetResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetDeploymentTarget404JSONResponse Error

func (response GetDeploymentTarget404JSONResponse) VisitGetDeploymentTargetResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type GetDeploymentTargetdefaultJSONResponse struct {
	Body       Error
	StatusCode int
}

func (response GetDeploymentTargetdefaultJSONResponse) VisitGetDeploymentTargetResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateDeploymentTargetRequestObject struct {
	DeploymentTargetId openapi_types.UUID `json:"deploymentTargetId"`
	Params             UpdateDeploymentTargetParams
	Body               *UpdateDeploymentTargetJSONRequestBody
}

type UpdateDeploymentTargetResponseObject interface {
	VisitUpdateDeploymentTargetResponse(w http.ResponseWriter) error
}

type UpdateDeploymentTarget200JSONResponse DeploymentTarget

func (response UpdateDeploymentTarget200JSONResponse) VisitUpdateDeploymentTargetResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateDeploymentTarget404JSONResponse Error

func (response UpdateDeploymentTarget404JSONResponse) VisitUpdateDeploymentTargetResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateDeploymentTarget409JSONResponse Error

func (response UpdateDeploymentTarget409JSONResponse) VisitUpdateDeploymentTargetResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateDeploymentTargetdefaultJSONResponse struct {
	Body       Error
	StatusCode int
}

func (response UpdateDeploymentTargetdefaultJSONResponse) VisitUpdateDeploymentTargetResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type CreateReleaseRequestObject struct {
	DeploymentTargetId openapi_types.UUID `json:"deploymentTargetId"`
	Params             CreateReleaseParams
	Body               *CreateReleaseJSONRequestBody
}

type CreateReleaseResponseObject interface {
	VisitCreateReleaseResponse(w http.ResponseWriter) error
}

type CreateRelease201JSONResponse ReleaseAcceptance

func (response CreateRelease201JSONResponse) VisitCreateReleaseResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)
	_, err := buf.WriteTo(w)
	return err
}

type CreateRelease400JSONResponse Error

func (response CreateRelease400JSONResponse) VisitCreateReleaseResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type CreateRelease404JSONResponse Error

func (response CreateRelease404JSONResponse) VisitCreateReleaseResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type CreateRelease409JSONResponse Error

func (response CreateRelease409JSONResponse) VisitCreateReleaseResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)
	_, err := buf.WriteTo(w)
	return err
}

type CreateReleasedefaultJSONResponse struct {
	Body       Error
	StatusCode int
}

func (response CreateReleasedefaultJSONResponse) VisitCreateReleaseResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type GetRuntimeSnapshotRequestObject struct {
	DeploymentTargetId openapi_types.UUID `json:"deploymentTargetId"`
}

type GetRuntimeSnapshotResponseObject interface {
	VisitGetRuntimeSnapshotResponse(w http.ResponseWriter) error
}

type GetRuntimeSnapshot200JSONResponse RuntimeSnapshot

func (response GetRuntimeSnapshot200JSONResponse) VisitGetRuntimeSnapshotResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetRuntimeSnapshot404JSONResponse Error

func (response GetRuntimeSnapshot404JSONResponse) VisitGetRuntimeSnapshotResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type GetRuntimeSnapshotdefaultJSONResponse struct {
	Body       Error
	StatusCode int
}

func (response GetRuntimeSnapshotdefaultJSONResponse) VisitGetRuntimeSnapshotResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type GetOperationRequestObject struct {
	OperationId openapi_types.UUID `json:"operationId"`
}

type GetOperationResponseObject interface {
	VisitGetOperationResponse(w http.ResponseWriter) error
}

type GetOperation200JSONResponse Operation

func (response GetOperation200JSONResponse) VisitGetOperationResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetOperation404JSONResponse Error

func (response GetOperation404JSONResponse) VisitGetOperationResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type GetOperationdefaultJSONResponse struct {
	Body       Error
	StatusCode int
}

func (response GetOperationdefaultJSONResponse) VisitGetOperationResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type CreateProjectRequestObject struct {
	Params CreateProjectParams
	Body   *CreateProjectJSONRequestBody
}

type CreateProjectResponseObject interface {
	VisitCreateProjectResponse(w http.ResponseWriter) error
}

type CreateProject201JSONResponse Project

func (response CreateProject201JSONResponse) VisitCreateProjectResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)
	_, err := buf.WriteTo(w)
	return err
}

type CreateProject409JSONResponse Error

func (response CreateProject409JSONResponse) VisitCreateProjectResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)
	_, err := buf.WriteTo(w)
	return err
}

type CreateProjectdefaultJSONResponse struct {
	Body       Error
	StatusCode int
}

func (response CreateProjectdefaultJSONResponse) VisitCreateProjectResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type GetProjectRequestObject struct {
	ProjectId openapi_types.UUID `json:"projectId"`
}

type GetProjectResponseObject interface {
	VisitGetProjectResponse(w http.ResponseWriter) error
}

type GetProject200JSONResponse Project

func (response GetProject200JSONResponse) VisitGetProjectResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetProject404JSONResponse Error

func (response GetProject404JSONResponse) VisitGetProjectResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type GetProjectdefaultJSONResponse struct {
	Body       Error
	StatusCode int
}

func (response GetProjectdefaultJSONResponse) VisitGetProjectResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type CreateApplicationRequestObject struct {
	ProjectId openapi_types.UUID `json:"projectId"`
	Params    CreateApplicationParams
	Body      *CreateApplicationJSONRequestBody
}

type CreateApplicationResponseObject interface {
	VisitCreateApplicationResponse(w http.ResponseWriter) error
}

type CreateApplication201JSONResponse Application

func (response CreateApplication201JSONResponse) VisitCreateApplicationResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)
	_, err := buf.WriteTo(w)
	return err
}

type CreateApplication404JSONResponse Error

func (response CreateApplication404JSONResponse) VisitCreateApplicationResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type CreateApplication409JSONResponse Error

func (response CreateApplication409JSONResponse) VisitCreateApplicationResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)
	_, err := buf.WriteTo(w)
	return err
}

type CreateApplicationdefaultJSONResponse struct {
	Body       Error
	StatusCode int
}

func (response CreateApplicationdefaultJSONResponse) VisitCreateApplicationResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type GetReleaseRequestObject struct {
	ReleaseId openapi_types.UUID `json:"releaseId"`
}

type GetReleaseResponseObject interface {
	VisitGetReleaseResponse(w http.ResponseWriter) error
}

type GetRelease200JSONResponse Release

func (response GetRelease200JSONResponse) VisitGetReleaseResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetRelease404JSONResponse Error

func (response GetRelease404JSONResponse) VisitGetReleaseResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type GetReleasedefaultJSONResponse struct {
	Body       Error
	StatusCode int
}

func (response GetReleasedefaultJSONResponse) VisitGetReleaseResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// GetApplication 查询应用
	// (GET /api/v1/applications/{applicationId})
	GetApplication(ctx context.Context, request GetApplicationRequestObject) (GetApplicationResponseObject, error)
	// CreateDeploymentTarget 创建部署目标
	// (POST /api/v1/applications/{applicationId}/deployment-targets)
	CreateDeploymentTarget(ctx context.Context, request CreateDeploymentTargetRequestObject) (CreateDeploymentTargetResponseObject, error)
	// GetDeploymentTarget 查询部署目标
	// (GET /api/v1/deployment-targets/{deploymentTargetId})
	GetDeploymentTarget(ctx context.Context, request GetDeploymentTargetRequestObject) (GetDeploymentTargetResponseObject, error)
	// UpdateDeploymentTarget 更新部署目标的可变期望配置
	// (PUT /api/v1/deployment-targets/{deploymentTargetId})
	UpdateDeploymentTarget(ctx context.Context, request UpdateDeploymentTargetRequestObject) (UpdateDeploymentTargetResponseObject, error)
	// CreateRelease 创建发布并接纳异步操作
	// (POST /api/v1/deployment-targets/{deploymentTargetId}/releases)
	CreateRelease(ctx context.Context, request CreateReleaseRequestObject) (CreateReleaseResponseObject, error)
	// GetRuntimeSnapshot 从 Kubernetes 查询部署目标的当前运行状态
	// (GET /api/v1/deployment-targets/{deploymentTargetId}/runtime-snapshot)
	GetRuntimeSnapshot(ctx context.Context, request GetRuntimeSnapshotRequestObject) (GetRuntimeSnapshotResponseObject, error)
	// GetOperation 查询异步操作
	// (GET /api/v1/operations/{operationId})
	GetOperation(ctx context.Context, request GetOperationRequestObject) (GetOperationResponseObject, error)
	// CreateProject 创建项目
	// (POST /api/v1/projects)
	CreateProject(ctx context.Context, request CreateProjectRequestObject) (CreateProjectResponseObject, error)
	// GetProject 查询项目
	// (GET /api/v1/projects/{projectId})
	GetProject(ctx context.Context, request GetProjectRequestObject) (GetProjectResponseObject, error)
	// CreateApplication 创建应用
	// (POST /api/v1/projects/{projectId}/applications)
	CreateApplication(ctx context.Context, request CreateApplicationRequestObject) (CreateApplicationResponseObject, error)
	// GetRelease 查询发布
	// (GET /api/v1/releases/{releaseId})
	GetRelease(ctx context.Context, request GetReleaseRequestObject) (GetReleaseResponseObject, error)
}

type StrictHandlerFunc func(ctx *gin.Context, request any) (any, error)
type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

type StrictGinServerOptions struct {
	// RequestErrorHandlerFunc is called when a request cannot be parsed or
	// decoded. It is invoked for JSON bind failures, form parse/bind errors,
	// multipart reader errors, media type parse errors, missing multipart
	// boundaries, and request body read errors. The default returns 400.
	RequestErrorHandlerFunc func(ctx *gin.Context, err error)
	// HandlerErrorFunc is called when the application handler (or any
	// middleware wrapping it) returns a non-nil error. The default returns 500.
	HandlerErrorFunc func(ctx *gin.Context, err error)
	// ResponseErrorHandlerFunc is called when the response object fails to
	// serialize (Visit*Response returns an error) or when the handler returns
	// an unexpected response type. The default returns 500.
	ResponseErrorHandlerFunc func(ctx *gin.Context, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictGinServerOptions{
		RequestErrorHandlerFunc: func(ctx *gin.Context, err error) {
			ctx.JSON(http.StatusBadRequest, gin.H{"msg": err.Error()})
		},
		HandlerErrorFunc: func(ctx *gin.Context, err error) {
			ctx.JSON(http.StatusInternalServerError, gin.H{"msg": err.Error()})
		},
		ResponseErrorHandlerFunc: func(ctx *gin.Context, err error) {
			ctx.JSON(http.StatusInternalServerError, gin.H{"msg": err.Error()})
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictGinServerOptions) ServerInterface {
	if options.RequestErrorHandlerFunc == nil {
		options.RequestErrorHandlerFunc = func(ctx *gin.Context, err error) {
			ctx.JSON(http.StatusBadRequest, gin.H{"msg": err.Error()})
		}
	}
	if options.HandlerErrorFunc == nil {
		options.HandlerErrorFunc = func(ctx *gin.Context, err error) {
			ctx.JSON(http.StatusInternalServerError, gin.H{"msg": err.Error()})
		}
	}
	if options.ResponseErrorHandlerFunc == nil {
		options.ResponseErrorHandlerFunc = func(ctx *gin.Context, err error) {
			ctx.JSON(http.StatusInternalServerError, gin.H{"msg": err.Error()})
		}
	}
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictGinServerOptions
}

// GetApplication operation middleware
func (sh *strictHandler) GetApplication(ctx *gin.Context, applicationId openapi_types.UUID) {
	var request GetApplicationRequestObject

	request.ApplicationId = applicationId

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetApplication(ctx, request.(GetApplicationRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetApplication")
	}

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(GetApplicationResponseObject); ok {
		if err := validResponse.VisitGetApplicationResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreateDeploymentTarget operation middleware
func (sh *strictHandler) CreateDeploymentTarget(ctx *gin.Context, applicationId openapi_types.UUID, params CreateDeploymentTargetParams) {
	var request CreateDeploymentTargetRequestObject

	request.ApplicationId = applicationId
	request.Params = params

	var body CreateDeploymentTargetJSONRequestBody
	if err := ctx.ShouldBindJSON(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(ctx, err)
		return
	}
	request.Body = &body

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.CreateDeploymentTarget(ctx, request.(CreateDeploymentTargetRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateDeploymentTarget")
	}

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(CreateDeploymentTargetResponseObject); ok {
		if err := validResponse.VisitCreateDeploymentTargetResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetDeploymentTarget operation middleware
func (sh *strictHandler) GetDeploymentTarget(ctx *gin.Context, deploymentTargetId openapi_types.UUID) {
	var request GetDeploymentTargetRequestObject

	request.DeploymentTargetId = deploymentTargetId

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetDeploymentTarget(ctx, request.(GetDeploymentTargetRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetDeploymentTarget")
	}

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(GetDeploymentTargetResponseObject); ok {
		if err := validResponse.VisitGetDeploymentTargetResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}

// UpdateDeploymentTarget operation middleware
func (sh *strictHandler) UpdateDeploymentTarget(ctx *gin.Context, deploymentTargetId openapi_types.UUID, params UpdateDeploymentTargetParams) {
	var request UpdateDeploymentTargetRequestObject

	request.DeploymentTargetId = deploymentTargetId
	request.Params = params

	var body UpdateDeploymentTargetJSONRequestBody
	if err := ctx.ShouldBindJSON(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(ctx, err)
		return
	}
	request.Body = &body

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.UpdateDeploymentTarget(ctx, request.(UpdateDeploymentTargetRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "UpdateDeploymentTarget")
	}

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(UpdateDeploymentTargetResponseObject); ok {
		if err := validResponse.VisitUpdateDeploymentTargetResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreateRelease operation middleware
func (sh *strictHandler) CreateRelease(ctx *gin.Context, deploymentTargetId openapi_types.UUID, params CreateReleaseParams) {
	var request CreateReleaseRequestObject

	request.DeploymentTargetId = deploymentTargetId
	request.Params = params

	var body CreateReleaseJSONRequestBody
	if err := ctx.ShouldBindJSON(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(ctx, err)
		return
	}
	request.Body = &body

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.CreateRelease(ctx, request.(CreateReleaseRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateRelease")
	}

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(CreateReleaseResponseObject); ok {
		if err := validResponse.VisitCreateReleaseResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetRuntimeSnapshot operation middleware
func (sh *strictHandler) GetRuntimeSnapshot(ctx *gin.Context, deploymentTargetId openapi_types.UUID) {
	var request GetRuntimeSnapshotRequestObject

	request.DeploymentTargetId = deploymentTargetId

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetRuntimeSnapshot(ctx, request.(GetRuntimeSnapshotRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetRuntimeSnapshot")
	}

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(GetRuntimeSnapshotResponseObject); ok {
		if err := validResponse.VisitGetRuntimeSnapshotResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetOperation operation middleware
func (sh *strictHandler) GetOperation(ctx *gin.Context, operationId openapi_types.UUID) {
	var request GetOperationRequestObject

	request.OperationId = operationId

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetOperation(ctx, request.(GetOperationRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetOperation")
	}

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(GetOperationResponseObject); ok {
		if err := validResponse.VisitGetOperationResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreateProject operation middleware
func (sh *strictHandler) CreateProject(ctx *gin.Context, params CreateProjectParams) {
	var request CreateProjectRequestObject

	request.Params = params

	var body CreateProjectJSONRequestBody
	if err := ctx.ShouldBindJSON(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(ctx, err)
		return
	}
	request.Body = &body

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.CreateProject(ctx, request.(CreateProjectRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateProject")
	}

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(CreateProjectResponseObject); ok {
		if err := validResponse.VisitCreateProjectResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetProject operation middleware
func (sh *strictHandler) GetProject(ctx *gin.Context, projectId openapi_types.UUID) {
	var request GetProjectRequestObject

	request.ProjectId = projectId

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetProject(ctx, request.(GetProjectRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetProject")
	}

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(GetProjectResponseObject); ok {
		if err := validResponse.VisitGetProjectResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreateApplication operation middleware
func (sh *strictHandler) CreateApplication(ctx *gin.Context, projectId openapi_types.UUID, params CreateApplicationParams) {
	var request CreateApplicationRequestObject

	request.ProjectId = projectId
	request.Params = params

	var body CreateApplicationJSONRequestBody
	if err := ctx.ShouldBindJSON(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(ctx, err)
		return
	}
	request.Body = &body

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.CreateApplication(ctx, request.(CreateApplicationRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateApplication")
	}

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(CreateApplicationResponseObject); ok {
		if err := validResponse.VisitCreateApplicationResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetRelease operation middleware
func (sh *strictHandler) GetRelease(ctx *gin.Context, releaseId openapi_types.UUID) {
	var request GetReleaseRequestObject

	request.ReleaseId = releaseId

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetRelease(ctx, request.(GetReleaseRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetRelease")
	}

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(GetReleaseResponseObject); ok {
		if err := validResponse.VisitGetReleaseResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"7FvdbhvHFX4VYpqrdmVSluXGvIqiBK2QohYU9UpQgBH3UNqE+5OZWTUqQcC1LMcurJ8gdu1aKpwEVmIg",
	"tdQ4hizLdv0w5S6lq75CMTtLcpY7XO0yMsU2uhG45M6cOd/5zs+cGVVRyTYd2wKLUVSsIgcTbAIDEjxN",
	"6GA6NgOrtPQBLPFvdKAlYjjMsC1URN6rL72bq/6Xq/VXW4dXVur7a971v4WPt5a9zafe9ZXG/Wve86uN",
	"xzf9rz4/3L3+7ytXkYYMPnoBsA4EacjCJqCiLG2Ii9MQgU9dg4COioy4oCFaWgAT83WY+LPfgTXPFlBx",
	"+PzbGjINq/n8tobYksMnpIwY1jyq1WrNoYFWY45TMUpY6FBFWNcN/hlXJontAGEGUFQs4woFDTnSV1VU",
	"IoAZ6GOMP5RtYmKGikjHDIaYYQKKSdaaQ94N0Iv9auiRmVzX0FWTCIAU4x1ifwwlNpFuGlpx5xXT1GSg",
	"Z1Awtj1xKD0cLSukSXjMtsTZc3wgFzce/CqhPQWfukBZRtCbyssmLxQiJh9OUFYadnGkc5SDGQPCyfjR",
	"DB760yz/Uxi6NDT7y7fiAHbgJMPSXf33wKnYSyZYbBqTeWC9YVCyLYYNC8ikTViolWG6JipeHB0dGQ3U",
	"Es9tKAyLwTwQFCw7sAGNjDx2FGV4PkAeLP7ODNJhESq2w5WRNO4CjxgtydY6tOiO2aQg38+RLlNQAUyh",
	"N9UNE8/DFJSBgFUCRbi+teJtfJ+jC/j86MXce8Y8UJZr3L9W31/11ne99Xu5y+MTuaM7W97yuvfyTuP2",
	"IxGtJUxGh89HQPn1SBSVj2aK1MElKM6+M/urd4Sk4gweKheGLs1WL16oHQ9UhxYqrDqdKiNOuB2SUkbO",
	"UsWlDMgUlJVhOOaecWc6zdQRWEQ5iRwYfnIA0JDr6NmUVKWeqHW0ViCRbCCrlRBhuiUreaEqer1PiE0y",
	"R2hdDbEJlIYwJisfzNB+X7Wwyw6QXuoW7qCmw8Zt1xLZoxn3C6q4H74tQgoDM/jwFuHcR7/It+vFfFhT",
	"5VvLGhMj+SThtJgQvPRG+A/cSOOYwbxNEt740DVN3OWFsmEZdCHbolK6nRGrnBW+F4T6tLUbwyQjfpRh",
	"5lLZfx2wdP6jhohrWeITdUslAB241DI2KqArXVt80Z4qXP05PQjFby4aBK/IYEWdugPnltJalPPdvF8i",
	"e6K/NYmdze0Gm6KWa84BiYSDbmXgT2deZr790SafABHOkYImoTLSOIkKbQ1URg6rzf/1rWCGzV2vG7qw",
	"OD1tpPSO6m8ibUhO91qsiI7HwkDshxZ26ILNjsuOIWrT0UFKwyg0iy0oJr4HC46VSuAwHOqXwZa2XICk",
	"KgmkTJcSqBg0zeGaJD5BuemYdQZ8a5Bcomdr8ZxoQd9hB7kndHJFutKSrsVDw7htCcNlNGL3kpuvA1Mx",
	"YULW6lr9JAMU1iqtvBPKSq7pQ10nbb3HRkecMQuhs6mU1+WYOmfbFcBWIi7qNoaQ0ZyxNTxBwV4dchEb",
	"FTxXgSm5h5W4fyk1aZN+BxMjnGIH0w7O739mUEbVOLbf+n03+/SYv3Sg3AjpcTi+/CwToAsW0EipFnzJ",
	"q2Srhb2yQrPnKJDFbIndsfXMRuGeoTBHwLz0YGTcbdkuKUUi5SfuHBALGNCkvU7a9XQ4lTLvh2uIAC2b",
	"LMY1BUXjrIkvtRNKTeFzEacKzajy9T8Ec5/1vNMnOz6FYZXteLf2Mpkz2GWH5ryD243bj+oHD+sv7vlr",
	"33k39rznPx79/ZvG/Wveyj+8l1dyv52ensx52180Dr4VHVtmsArIc4xNTiANLQKhYvLCueFzhcCLHbCw",
	"Y6AiGjlXODeCgnbuQoBaHjtGfnE4L+V6mq9GMn+Nvxc2YFvFGfcx9Btg8jmbFjlZnKmKE0Auqn3+11lT",
	"dD/9O8Z/a7N8MHVsiwoqnS8UmowC0QGTZOU/DhNfe/6kqCRrFVivo8ceGOtw91t/eYXje6Fw4cREi75k",
	"V6H1/VXv8T1v65HIFmXsVtibl324+8z/4ar38IfDp9uBQ9BmOwP5D7YPd78Riwt+SsOofDuIDYmdjjiY",
	"tqmCZeoztj6zTVMj115CvuMcXfAziInv2qIgOxEbJZ841qLRimtZi/nJ8IktJmYUBXeOlh81Xj1pbO74",
	"X33uPXvi3dj0XhycptdcKFzqg9zgOsTR7R3v2ZPGi/Ugtq/xZWzcEs40KP4r7CEbKeLFcUfNV+OVTGKK",
	"6MlzldXSYCaLrE7Q57whix7Q7BFln4YcV8Ekddl5GmQamFyQXImnygWF08wF/uZT/6//PH1POMsIEZ8M",
	"rCKDxTchwd0Rf+uBv7V5tLLaeLXTS5rIhzv0Y6u9qVY7+Ofr3crLQn0u8OJnCSpmr3/h7S/X99e8f614",
	"D681Nq6L66G82lt74D3ekGu+Qh/8XLrcVN9f9e/t+ls3/Ts3YregxCtn8WcQK1JBKu/5nr+23Tj40Xt5",
	"1X+8LXjVW+QRjcYhKrWou1Wsnd3s/7OCtVM9hXk+aHVCc4evNw6/vuXf3fNef99Y+e4/LzeFEx3uvD66",
	"u+Pf3cu12pW5+v5BTm4pn9W4qIjqL9ZyEp7xkpen1+CSvYC68Zc9/8qfIyRvMZTmqxJbE7dd7dPZNPSV",
	"hw8qb6Xz5rgBwv9I6O/eSggd1J5ct5AZnvEeW4Q1L83E+DNI9VHHPfI+10dNiFQx6evnjc2djo7XWZ6P",
	"dZ4CmJT8zFdbtxESI11XnirinHy/YTCj3LGU6nf/KBA6qJ2jdOyJHEYcF/ayHmmdDKUGbNup+I+uPofW",
	"VGdw/T9QULjDWVhXbN/iB4LN3k++2rqnkRjWs/SA5KvjA7rpal187NI/6fdxcti0GczSNVgcH1r7bwAA",
	"AP//",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
